var dir_99f93e246f30dd289b3aac13f5191b89 =
[
    [ "ra8_io.h", "ra8__io_8h.html", null ],
    [ "ra8_io_blockdev.h", "ra8__io__blockdev_8h.html", "ra8__io__blockdev_8h" ],
    [ "ra8_io_blockdev_cache.h", "ra8__io__blockdev__cache_8h.html", "ra8__io__blockdev__cache_8h" ],
    [ "ra8_io_blockdev_mram.h", "ra8__io__blockdev__mram_8h.html", "ra8__io__blockdev__mram_8h" ],
    [ "ra8_io_blockdev_ram.h", "ra8__io__blockdev__ram_8h.html", "ra8__io__blockdev__ram_8h" ],
    [ "ra8_io_blockdev_sdhi.h", "ra8__io__blockdev__sdhi_8h.html", "ra8__io__blockdev__sdhi_8h" ],
    [ "ra8_io_blockdev_sdram.h", "ra8__io__blockdev__sdram_8h.html", "ra8__io__blockdev__sdram_8h" ],
    [ "ra8_io_blockdev_sdspi.h", "ra8__io__blockdev__sdspi_8h.html", "ra8__io__blockdev__sdspi_8h" ],
    [ "ra8_io_blockdev_vsource.h", "ra8__io__blockdev__vsource_8h.html", "ra8__io__blockdev__vsource_8h" ],
    [ "ra8_io_blockdev_xspi.h", "ra8__io__blockdev__xspi_8h.html", "ra8__io__blockdev__xspi_8h" ],
    [ "ra8_io_compress.h", "ra8__io__compress_8h.html", "ra8__io__compress_8h" ],
    [ "ra8_io_fsfmt.h", "ra8__io__fsfmt_8h.html", "ra8__io__fsfmt_8h" ],
    [ "ra8_io_i2c_bus.h", "ra8__io__i2c__bus_8h.html", "ra8__io__i2c__bus_8h" ],
    [ "ra8_io_i2c_bus_i3c_compat.h", "ra8__io__i2c__bus__i3c__compat_8h.html", "ra8__io__i2c__bus__i3c__compat_8h" ],
    [ "ra8_io_i2c_bus_riic.h", "ra8__io__i2c__bus__riic_8h.html", "ra8__io__i2c__bus__riic_8h" ],
    [ "ra8_io_log.h", "ra8__io__log_8h.html", "ra8__io__log_8h" ],
    [ "ra8_io_spi_bus.h", "ra8__io__spi__bus_8h.html", "ra8__io__spi__bus_8h" ],
    [ "ra8_io_spi_bus_sci_spi.h", "ra8__io__spi__bus__sci__spi_8h.html", "ra8__io__spi__bus__sci__spi_8h" ],
    [ "ra8_io_spi_bus_spi_b.h", "ra8__io__spi__bus__spi__b_8h.html", "ra8__io__spi__bus__spi__b_8h" ],
    [ "ra8_io_stream.h", "ra8__io__stream_8h.html", "ra8__io__stream_8h" ],
    [ "ra8_io_stream_blockdev.h", "ra8__io__stream__blockdev_8h.html", "ra8__io__stream__blockdev_8h" ],
    [ "ra8_io_stream_ram.h", "ra8__io__stream__ram_8h.html", "ra8__io__stream__ram_8h" ],
    [ "ra8_io_stream_uart.h", "ra8__io__stream__uart_8h.html", "ra8__io__stream__uart_8h" ],
    [ "ra8_io_stream_usbcdc.h", "ra8__io__stream__usbcdc_8h.html", "ra8__io__stream__usbcdc_8h" ],
    [ "ra8_io_vfs.h", "ra8__io__vfs_8h.html", "ra8__io__vfs_8h" ],
    [ "ra8_io_vfs_compress.h", "ra8__io__vfs__compress_8h.html", "ra8__io__vfs__compress_8h" ]
];