var dir_47cec3338b518b7f452a5f2c989f4acd =
[
    [ "ra8_io_blockdev.c", "ra8__io__blockdev_8c.html", "ra8__io__blockdev_8c" ],
    [ "ra8_io_blockdev_cache.c", "ra8__io__blockdev__cache_8c.html", "ra8__io__blockdev__cache_8c" ],
    [ "ra8_io_blockdev_internal.h", "ra8__io__blockdev__internal_8h.html", "ra8__io__blockdev__internal_8h" ],
    [ "ra8_io_blockdev_mram.c", "ra8__io__blockdev__mram_8c.html", "ra8__io__blockdev__mram_8c" ],
    [ "ra8_io_blockdev_ram.c", "ra8__io__blockdev__ram_8c.html", "ra8__io__blockdev__ram_8c" ],
    [ "ra8_io_blockdev_sdhi.c", "ra8__io__blockdev__sdhi_8c.html", "ra8__io__blockdev__sdhi_8c" ],
    [ "ra8_io_blockdev_sdram.c", "ra8__io__blockdev__sdram_8c.html", "ra8__io__blockdev__sdram_8c" ],
    [ "ra8_io_blockdev_sdspi.c", "ra8__io__blockdev__sdspi_8c.html", "ra8__io__blockdev__sdspi_8c" ],
    [ "ra8_io_blockdev_vsource.c", "ra8__io__blockdev__vsource_8c.html", "ra8__io__blockdev__vsource_8c" ],
    [ "ra8_io_blockdev_xspi.c", "ra8__io__blockdev__xspi_8c.html", "ra8__io__blockdev__xspi_8c" ],
    [ "ra8_io_compress.c", "ra8__io__compress_8c.html", "ra8__io__compress_8c" ],
    [ "ra8_io_fsfmt.c", "ra8__io__fsfmt_8c.html", "ra8__io__fsfmt_8c" ],
    [ "ra8_io_i2c_bus.c", "ra8__io__i2c__bus_8c.html", "ra8__io__i2c__bus_8c" ],
    [ "ra8_io_i2c_bus_i3c_compat.c", "ra8__io__i2c__bus__i3c__compat_8c.html", "ra8__io__i2c__bus__i3c__compat_8c" ],
    [ "ra8_io_i2c_bus_internal.h", "ra8__io__i2c__bus__internal_8h.html", "ra8__io__i2c__bus__internal_8h" ],
    [ "ra8_io_i2c_bus_riic.c", "ra8__io__i2c__bus__riic_8c.html", "ra8__io__i2c__bus__riic_8c" ],
    [ "ra8_io_log.c", "ra8__io__log_8c.html", "ra8__io__log_8c" ],
    [ "ra8_io_spi_bus.c", "ra8__io__spi__bus_8c.html", "ra8__io__spi__bus_8c" ],
    [ "ra8_io_spi_bus_internal.h", "ra8__io__spi__bus__internal_8h.html", "ra8__io__spi__bus__internal_8h" ],
    [ "ra8_io_spi_bus_sci_spi.c", "ra8__io__spi__bus__sci__spi_8c.html", "ra8__io__spi__bus__sci__spi_8c" ],
    [ "ra8_io_spi_bus_spi_b.c", "ra8__io__spi__bus__spi__b_8c.html", "ra8__io__spi__bus__spi__b_8c" ],
    [ "ra8_io_stream.c", "ra8__io__stream_8c.html", "ra8__io__stream_8c" ],
    [ "ra8_io_stream_blockdev.c", "ra8__io__stream__blockdev_8c.html", "ra8__io__stream__blockdev_8c" ],
    [ "ra8_io_stream_internal.h", "ra8__io__stream__internal_8h.html", "ra8__io__stream__internal_8h" ],
    [ "ra8_io_stream_ram.c", "ra8__io__stream__ram_8c.html", "ra8__io__stream__ram_8c" ],
    [ "ra8_io_stream_uart.c", "ra8__io__stream__uart_8c.html", "ra8__io__stream__uart_8c" ],
    [ "ra8_io_stream_usbcdc.c", "ra8__io__stream__usbcdc_8c.html", "ra8__io__stream__usbcdc_8c" ],
    [ "ra8_io_vfs.c", "ra8__io__vfs_8c.html", "ra8__io__vfs_8c" ],
    [ "ra8_io_vfs_compress.c", "ra8__io__vfs__compress_8c.html", "ra8__io__vfs__compress_8c" ]
];