var group__grp__core =
[
    [ "ra8_attributes.h", "ra8__attributes_8h.html", null ],
    [ "ra8_bit_constants.h", "ra8__bit__constants_8h.html", null ],
    [ "ra8_boot_entry.h", "ra8__boot__entry_8h.html", null ],
    [ "ra8_check.h", "ra8__check_8h.html", null ],
    [ "ra8_crashlog.h", "ra8__crashlog_8h.html", null ],
    [ "ra8_decomp_limits.h", "ra8__decomp__limits_8h.html", null ],
    [ "ra8_device.h", "ra8__device_8h.html", null ],
    [ "ra8_err.h", "ra8__err_8h.html", null ],
    [ "ra8_error_handler.h", "ra8__error__handler_8h.html", null ],
    [ "ra8_error_interface.h", "ra8__error__interface_8h.html", null ],
    [ "ra8_exception.h", "ra8__exception_8h.html", null ],
    [ "ra8_gpio_constants.h", "ra8__gpio__constants_8h.html", null ],
    [ "ra8_infrastructure.h", "ra8__infrastructure_8h.html", null ],
    [ "ra8_log.h", "ra8__log_8h.html", null ],
    [ "ra8_off_target_config.h", "ra8__off__target__config_8h.html", null ],
    [ "ra8_pin_interface.h", "ra8__pin__interface_8h.html", null ],
    [ "ra8_pin_validator.h", "ra8__pin__validator_8h.html", null ],
    [ "ra8_port_constants.h", "ra8__port__constants_8h.html", null ],
    [ "ra8_register_guard.h", "ra8__register__guard_8h.html", null ],
    [ "ra8_sbrk_trap.h", "ra8__sbrk__trap_8h.html", null ],
    [ "ra8_secure.h", "ra8__secure_8h.html", null ],
    [ "ra8_stack_budget.h", "ra8__stack__budget_8h.html", null ],
    [ "ra8_time.h", "ra8__time_8h.html", null ],
    [ "ra8_time_constants.h", "ra8__time__constants_8h.html", null ],
    [ "ra8_time_interface.h", "ra8__time__interface_8h.html", null ],
    [ "ra8_crashlog_internal.h", "ra8__crashlog__internal_8h.html", null ]
];