var ra8_docs =
[
    [ "Architecture Decision Records (adr)", "ra8_docsub_adr.html", "ra8_docsub_adr" ],
    [ "Design", "ra8_docsub_design.html", "ra8_docsub_design" ],
    [ "Binary format specifications (formats)", "ra8_docsub_formats.html", "ra8_docsub_formats" ],
    [ "Qualification kit (qualification)", "ra8_docsub_qualification.html", "ra8_docsub_qualification" ],
    [ "Datasheet reference (reference)", "ra8_docsub_reference.html", "ra8_docsub_reference" ],
    [ "SOUP component justifications (SOUP)", "ra8_docsub_SOUP.html", "ra8_docsub_SOUP" ],
    [ "RA8D2 Acronym Glossary", "md_docs_2ACRONYMS.html", null ],
    [ "AI Attribution Policy", "md_docs_2AI__ATTRIBUTION__POLICY.html", null ],
    [ "RA8_* Annotation Contracts", "md_docs_2ANNOTATIONS.html", null ],
    [ "ra8-firmware architecture", "md_docs_2ARCHITECTURE.html", null ],
    [ "Certification Scope", "md_docs_2CERTIFICATION__SCOPE.html", null ],
    [ "The CI fleet: declared, tuned, and scheduled", "md_docs_2CI__FLEET.html", null ],
    [ "Citation Policy", "md_docs_2CITATION__POLICY.html", null ],
    [ "E-Book Content Licensing", "md_docs_2CONTENT__LICENSING.html", null ],
    [ "Coverage (statement + branch)", "md_docs_2COVERAGE.html", null ],
    [ "Debugging the EK-RA8D2", "md_docs_2DEBUG.html", null ],
    [ "Doxygen HTML Documentation", "md_docs_2DOCS.html", null ],
    [ "DRIVER_STATUS", "md_docs_2DRIVER__STATUS.html", null ],
    [ "Dual-core (CPU0 / CPU1) on the RA8D2", "md_docs_2DUAL__CORE.html", null ],
    [ "EPUB Reader &ndash; Supported Conformance Subset", "md_docs_2EPUB__CONFORMANCE.html", null ],
    [ "Fuzzing", "md_docs_2FUZZING.html", null ],
    [ "Hardware Bring-up Report (EK-RA8D2 v1)", "md_docs_2HARDWARE__BRINGUP.html", null ],
    [ "Hardware-in-the-Loop (HIL) Developer Workflow", "md_docs_2HIL__DEVELOPER__WORKFLOW.html", null ],
    [ "HIL Suite", "md_docs_2HIL__SUITE.html", null ],
    [ "Developer IDE Integration", "md_docs_2IDE.html", null ],
    [ "Project infrastructure", "md_docs_2INFRASTRUCTURE.html", null ],
    [ "MC/DC Coverage (DO-178C Level B)", "md_docs_2MCDC.html", null ],
    [ "MC/DC Deactivated-Decision Catalog", "md_docs_2MCDC__DEACTIVATIONS.html", null ],
    [ "MC/DC Coverage Gap Audit", "md_docs_2MCDC__GAPS.html", null ],
    [ "RA8D2 Memory Map &ndash; Quick Reference", "md_docs_2MEMORY__MAP.html", null ],
    [ "MISRA-C 2012 Compliance", "md_docs_2MISRA.html", null ],
    [ "Module tour (<span class=\"tt\">libs/</span>)", "md_docs_2MODULES.html", null ],
    [ "Host-side Performance Benchmarks", "md_docs_2PERFORMANCE.html", null ],
    [ "Python Environments and Lock Maintenance", "md_docs_2PYTHON__ENVIRONMENTS.html", null ],
    [ "Qualification Basis &ndash; IEC 61508 SIL 3 / DO-178C Level B", "md_docs_2QUALIFICATION__ROADMAP.html", null ],
    [ "Ring and World tagging", "md_docs_2RING__AND__WORLD.html", null ],
    [ "HAL Completion Record (Historical)", "md_docs_2ROADMAP.html", null ],
    [ "Root-of-Trust Signing Key", "md_docs_2ROOT__OF__TRUST.html", null ],
    [ "Stack-Usage Bounding", "md_docs_2STACK__USAGE.html", null ],
    [ "Static Analysis: Clang Static Analyzer (scan-build)", "md_docs_2STATIC__ANALYSIS.html", null ],
    [ "ra8-firmware style guide", "md_docs_2STYLE__GUIDE.html", null ],
    [ "TOOLCHAIN", "md_docs_2TOOLCHAIN.html", null ],
    [ "Vendor Blobs (Renesas-Only, Not Shipped)", "md_docs_2VENDOR__BLOBS.html", null ],
    [ "Workflow automation: <span class=\"tt\">work</span>", "md_docs_2WORKFLOW__AUTOMATION.html", null ],
    [ "Zig Library Migration", "md_docs_2ZIG__MIGRATION.html", null ]
];