var searchData=
[
  ['s_20manual_20ndash_20chapter_20map_0',['RA8D2 Hardware User&apos;s Manual &amp;ndash; Chapter Map',['../md_docs_2reference_2CHAPTER__MAP.html',1,'ra8_docsub_reference']]],
  ['sas_1',['Software Accomplishment Summary (SAS)',['../md_docs_2qualification_2SAS.html',1,'ra8_docsub_qualification']]],
  ['scan_20build_2',['Static Analysis: Clang Static Analyzer (scan-build)',['../md_docs_2STATIC__ANALYSIS.html',1,'ra8_docs']]],
  ['scheduled_3',['The CI fleet: declared, tuned, and scheduled',['../md_docs_2CI__FLEET.html',1,'ra8_docs']]],
  ['scmp_4',['Software Configuration Management Plan (SCMP)',['../md_docs_2qualification_2SCMP.html',1,'ra8_docsub_qualification']]],
  ['scope_5',['Certification Scope',['../md_docs_2CERTIFICATION__SCOPE.html',1,'ra8_docs']]],
  ['script_20auto_20classification_6',['ADR-0004: DO-178C 6.4.4.3 deactivated-condition policy with regen-script auto-classification',['../md_docs_2adr_20004-deactivated-condition-policy.html',1,'ra8_docsub_adr']]],
  ['sdd_7',['Software Design Description (SDD)',['../md_docs_2qualification_2SDD.html',1,'ra8_docsub_qualification']]],
  ['sdp_8',['Software Development Plan (SDP)',['../md_docs_2qualification_2SDP.html',1,'ra8_docsub_qualification']]],
  ['secure_20image_20rot_20header_9',['NSR1 &amp;ndash; The Non-Secure Image RoT Header',['../md_docs_2formats_2NSR1.html',1,'ra8_docsub_formats']]],
  ['setup_20ek_20ra8d2_20ndash_20deprecated_10',['Hardware-in-the-Loop CI Runner Setup (EK-RA8D2) &amp;ndash; DEPRECATED',['../md_docs_2qualification_2HW__IN__LOOP__RUNNER.html',1,'ra8_docsub_qualification']]],
  ['shipped_11',['Vendor Blobs (Renesas-Only, Not Shipped)',['../md_docs_2VENDOR__BLOBS.html',1,'ra8_docs']]],
  ['side_20performance_20benchmarks_12',['Host-side Performance Benchmarks',['../md_docs_2PERFORMANCE.html',1,'ra8_docs']]],
  ['signed_20image_20trailer_13',['ROT1 &amp;ndash; The Root-of-Trust Signed-Image Trailer',['../md_docs_2formats_2ROT1.html',1,'ra8_docsub_formats']]],
  ['signing_20key_14',['Root-of-Trust Signing Key',['../md_docs_2ROOT__OF__TRUST.html',1,'ra8_docs']]],
  ['sil_203_20do_20178c_20level_20b_15',['Qualification Roadmap &amp;ndash; IEC 61508 SIL 3 / DO-178C Level B',['../md_docs_2QUALIFICATION__ROADMAP.html',1,'ra8_docs']]],
  ['sil_203_20do_20178c_20level_20b_20as_20the_20qualification_20target_16',['ADR-0001: Adopt IEC 61508 SIL 3 / DO-178C Level B as the qualification target',['../md_docs_2adr_20001-iec-61508-sil-3-do-178c-level-b-target.html',1,'ra8_docsub_adr']]],
  ['size_20report_17',['ra8-firmware &amp;ndash; per-application size report',['../md_docs_2APP__SIZES.html',1,'ra8_docs']]],
  ['software_20accomplishment_20summary_20sas_18',['Software Accomplishment Summary (SAS)',['../md_docs_2qualification_2SAS.html',1,'ra8_docsub_qualification']]],
  ['software_20aspects_20of_20certification_20psac_19',['Plan for Software Aspects of Certification (PSAC)',['../md_docs_2qualification_2PSAC.html',1,'ra8_docsub_qualification']]],
  ['software_20configuration_20management_20plan_20scmp_20',['Software Configuration Management Plan (SCMP)',['../md_docs_2qualification_2SCMP.html',1,'ra8_docsub_qualification']]],
  ['software_20design_20description_20sdd_21',['Software Design Description (SDD)',['../md_docs_2qualification_2SDD.html',1,'ra8_docsub_qualification']]],
  ['software_20development_20plan_20sdp_22',['Software Development Plan (SDP)',['../md_docs_2qualification_2SDP.html',1,'ra8_docsub_qualification']]],
  ['software_20quality_20assurance_20plan_20sqap_23',['Software Quality Assurance Plan (SQAP)',['../md_docs_2qualification_2SQAP.html',1,'ra8_docsub_qualification']]],
  ['software_20requirements_20specification_20srs_24',['Software Requirements Specification (SRS)',['../md_docs_2qualification_2SRS.html',1,'ra8_docsub_qualification']]],
  ['software_20verification_20cases_20procedures_20svcp_25',['Software Verification Cases &amp;amp; Procedures (SVCP)',['../md_docs_2qualification_2SVCP.html',1,'ra8_docsub_qualification']]],
  ['software_20verification_20plan_20svp_26',['Software Verification Plan (SVP)',['../md_docs_2qualification_2SVP.html',1,'ra8_docsub_qualification']]],
  ['software_20verification_20results_20svr_27',['Software Verification Results (SVR)',['../md_docs_2qualification_2SVR.html',1,'ra8_docsub_qualification']]],
  ['soup_28',['SOUP component justifications (SOUP)',['../ra8_docsub_SOUP.html',1,'ra8_docs']]],
  ['soup_20component_20justifications_20soup_29',['SOUP component justifications (SOUP)',['../ra8_docsub_SOUP.html',1,'ra8_docs']]],
  ['soup_20justification_3a_20apache_20nimble_30',['SOUP Justification: Apache NimBLE',['../md_docs_2SOUP_2nimble.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20arm_20ethos_20u_20vela_20host_20build_20tool_31',['SOUP Justification: Arm Ethos-U Vela (host build tool)',['../md_docs_2SOUP_2vela.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20eclipse_20levelx_32',['SOUP Justification: Eclipse LevelX',['../md_docs_2SOUP_2levelx.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20eclipse_20netx_20duo_33',['SOUP Justification: Eclipse NetX Duo',['../md_docs_2SOUP_2netxduo.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20eclipse_20threadx_34',['SOUP Justification: Eclipse ThreadX',['../md_docs_2SOUP_2threadx.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20eclipse_20usbx_35',['SOUP Justification: Eclipse USBX',['../md_docs_2SOUP_2usbx.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20espressif_20esp_20hosted_20mcu_20co_20processor_20firmware_36',['SOUP Justification: Espressif esp-hosted-mcu (co-processor firmware)',['../md_docs_2SOUP_2esp-hosted.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20espressif_20esp_20hosted_20mcu_20host_20driver_37',['SOUP Justification: Espressif esp-hosted-mcu (host driver)',['../md_docs_2SOUP_2esp-hosted-host.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20flatbuffers_38',['SOUP Justification: FlatBuffers',['../md_docs_2SOUP_2flatbuffers.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20gemmlowp_20fixed_20point_20headers_39',['SOUP Justification: gemmlowp (fixed-point headers)',['../md_docs_2SOUP_2gemmlowp.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20libwebp_20webp_20decoder_40',['SOUP Justification: libwebp (WebP decoder)',['../md_docs_2SOUP_2libwebp.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20litehtml_41',['SOUP Justification: litehtml',['../md_docs_2SOUP_2litehtml.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20mbed_20tls_42',['SOUP Justification: Mbed TLS',['../md_docs_2SOUP_2mbedtls.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20miniz_43',['SOUP Justification: miniz',['../md_docs_2SOUP_2miniz.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20ruy_20profiler_20instrumentation_20stub_44',['SOUP Justification: ruy (profiler instrumentation stub)',['../md_docs_2SOUP_2ruy.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20stb_20image_20truetype_45',['SOUP Justification: stb (image / truetype)',['../md_docs_2SOUP_2stb.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20tensorflow_20lite_20for_20microcontrollers_46',['SOUP Justification: TensorFlow Lite for Microcontrollers',['../md_docs_2SOUP_2tflite-micro.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20tf_20psa_20crypto_47',['SOUP Justification: TF-PSA-Crypto',['../md_docs_2SOUP_2tf-psa-crypto.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20tinyxml_202_48',['SOUP Justification: TinyXML-2',['../md_docs_2SOUP_2tinyxml2.html',1,'ra8_docsub_SOUP']]],
  ['soup_20justification_3a_20xz_20embedded_20decode_20only_49',['SOUP Justification: XZ Embedded (decode-only)',['../md_docs_2SOUP_2xz__embedded.html',1,'ra8_docsub_SOUP']]],
  ['specification_20srs_50',['Software Requirements Specification (SRS)',['../md_docs_2qualification_2SRS.html',1,'ra8_docsub_qualification']]],
  ['specifications_20formats_51',['Binary format specifications (formats)',['../ra8_docsub_formats.html',1,'ra8_docs']]],
  ['specifications_20ndash_20overview_52',['Binary Format Specifications &amp;ndash; Overview',['../md_docs_2formats_2BINARY__FORMATS.html',1,'ra8_docsub_formats']]],
  ['sqap_53',['Software Quality Assurance Plan (SQAP)',['../md_docs_2qualification_2SQAP.html',1,'ra8_docsub_qualification']]],
  ['srs_54',['Software Requirements Specification (SRS)',['../md_docs_2qualification_2SRS.html',1,'ra8_docsub_qualification']]],
  ['stack_20usage_20bounding_55',['Stack-Usage Bounding',['../md_docs_2STACK__USAGE.html',1,'ra8_docs']]],
  ['statement_20branch_56',['Coverage (statement + branch)',['../md_docs_2COVERAGE.html',1,'ra8_docs']]],
  ['static_20analysis_3a_20clang_20static_20analyzer_20scan_20build_57',['Static Analysis: Clang Static Analyzer (scan-build)',['../md_docs_2STATIC__ANALYSIS.html',1,'ra8_docs']]],
  ['static_20analyzer_20scan_20build_58',['Static Analysis: Clang Static Analyzer (scan-build)',['../md_docs_2STATIC__ANALYSIS.html',1,'ra8_docs']]],
  ['status_20matrix_59',['Driver Status Matrix',['../md_docs_2DRIVER__STATUS.html',1,'ra8_docs']]],
  ['stb_20image_20truetype_60',['SOUP Justification: stb (image / truetype)',['../md_docs_2SOUP_2stb.html',1,'ra8_docsub_SOUP']]],
  ['steps_61',['steps',['../ra8_ex_ek_ra8d2_hw_pending_manual.html',1,'Manual (jumper / button steps)'],['../ra8_ex_ek_ra8d2_hw_validated_manual.html',1,'Manual (jumper / button steps)']]],
  ['stock_20evaluation_20kit_62',['EK-RA8D2 (stock evaluation kit)',['../ra8_ex_ek_ra8d2.html',1,'ra8_examples']]],
  ['stub_63',['SOUP Justification: ruy (profiler instrumentation stub)',['../md_docs_2SOUP_2ruy.html',1,'ra8_docsub_SOUP']]],
  ['style_20guide_64',['ra8-firmware style guide',['../md_docs_2STYLE__GUIDE.html',1,'ra8_docs']]],
  ['subset_65',['EPUB Reader &amp;ndash; Supported Conformance Subset',['../md_docs_2EPUB__CONFORMANCE.html',1,'ra8_docs']]],
  ['summary_20sas_66',['Software Accomplishment Summary (SAS)',['../md_docs_2qualification_2SAS.html',1,'ra8_docsub_qualification']]],
  ['supported_20conformance_20subset_67',['EPUB Reader &amp;ndash; Supported Conformance Subset',['../md_docs_2EPUB__CONFORMANCE.html',1,'ra8_docs']]],
  ['svcp_68',['Software Verification Cases &amp;amp; Procedures (SVCP)',['../md_docs_2qualification_2SVCP.html',1,'ra8_docsub_qualification']]],
  ['svp_69',['Software Verification Plan (SVP)',['../md_docs_2qualification_2SVP.html',1,'ra8_docsub_qualification']]],
  ['svr_70',['Software Verification Results (SVR)',['../md_docs_2qualification_2SVR.html',1,'ra8_docsub_qualification']]],
  ['symbols_20via_20lt_20module_20gt_20_5finternal_20h_71',['ADR-0003: Test-only access to internal symbols via &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_internal.h&lt;/span&gt;',['../md_docs_2adr_20003-test-only-internal-headers.html',1,'ra8_docsub_adr']]]
];
