var searchData=
[
  ['ra8_20firmware_0',['ra8-firmware',['../index.html',1,'']]],
  ['ra8_20firmware_20architecture_1',['ra8-firmware architecture',['../md_docs_2ARCHITECTURE.html',1,'ra8_docs']]],
  ['ra8_20firmware_20style_20guide_2',['ra8-firmware style guide',['../md_docs_2STYLE__GUIDE.html',1,'ra8_docs']]],
  ['ra8_5f_20annotation_20contracts_3',['RA8_* Annotation Contracts',['../md_docs_2ANNOTATIONS.html',1,'ra8_docs']]],
  ['ra8d2_4',['RA8D2',['../md_docs_2DEBUG.html',1,'Debugging the EK-RA8D2'],['../md_docs_2DUAL__CORE.html',1,'Dual-core (CPU0 / CPU1) on the RA8D2']]],
  ['ra8d2_20acronym_20glossary_5',['RA8D2 Acronym Glossary',['../md_docs_2ACRONYMS.html',1,'ra8_docs']]],
  ['ra8d2_20hardware_20user_20s_20manual_20ndash_20chapter_20map_6',['RA8D2 Hardware User&apos;s Manual &amp;ndash; Chapter Map',['../md_docs_2reference_2CHAPTER__MAP.html',1,'ra8_docsub_reference']]],
  ['ra8d2_20memory_20map_20ndash_20quick_20reference_7',['RA8D2 Memory Map &amp;ndash; Quick Reference',['../md_docs_2MEMORY__MAP.html',1,'ra8_docs']]],
  ['ra8d2_20ndash_20durable_20difference_20reference_8',['RA8P1 vs RA8D2 &amp;ndash; durable difference reference',['../md_docs_2reference_2ra8p1__vs__ra8d2.html',1,'ra8_docsub_reference']]],
  ['ra8d2_20stock_20evaluation_20kit_9',['EK-RA8D2 (stock evaluation kit)',['../ra8_ex_ek_ra8d2.html',1,'ra8_examples']]],
  ['ra8d2_20v1_10',['Hardware Bring-up Report (EK-RA8D2 v1)',['../md_docs_2HARDWARE__BRINGUP.html',1,'ra8_docs']]],
  ['ra8p1_20foundation_11',['RA8P1 foundation',['../ra8_ex_ra8p1_foundation.html',1,'ra8_examples']]],
  ['ra8p1_20vs_20ra8d2_20ndash_20durable_20difference_20reference_12',['RA8P1 vs RA8D2 &amp;ndash; durable difference reference',['../md_docs_2reference_2ra8p1__vs__ra8d2.html',1,'ra8_docsub_reference']]],
  ['rabook_20container_13',['RBKC &amp;ndash; The Chunked &lt;span class=&quot;tt&quot;&gt;.rabook&lt;/span&gt; Container',['../md_docs_2formats_2RBKC.html',1,'ra8_docsub_formats']]],
  ['radio_20just_20hil_3a_3ac6_14',['ESP32-C6 companion radio (just hil::c6)',['../ra8_ex_ek_ra8d2_hw_validated_c6.html',1,'ra8_ex_ek_ra8d2_hw_validated']]],
  ['rbkc_20ndash_20the_20chunked_20rabook_20container_15',['RBKC &amp;ndash; The Chunked &lt;span class=&quot;tt&quot;&gt;.rabook&lt;/span&gt; Container',['../md_docs_2formats_2RBKC.html',1,'ra8_docsub_formats']]],
  ['re_20validation_16',['HIL &amp;ndash; needs re-validation',['../ra8_ex_ek_ra8d2_hil_needs_revalidation.html',1,'ra8_ex_ek_ra8d2']]],
  ['reader_20ndash_20supported_20conformance_20subset_17',['EPUB Reader &amp;ndash; Supported Conformance Subset',['../md_docs_2EPUB__CONFORMANCE.html',1,'ra8_docs']]],
  ['record_20historical_18',['HAL Completion Record (Historical)',['../md_docs_2ROADMAP.html',1,'ra8_docs']]],
  ['records_20adr_19',['Architecture Decision Records (adr)',['../ra8_docsub_adr.html',1,'ra8_docs']]],
  ['reference_20',['RA8D2 Memory Map &amp;ndash; Quick Reference',['../md_docs_2MEMORY__MAP.html',1,'ra8_docs']]],
  ['reference_21',['reference',['../ra8_docsub_reference.html',1,'Datasheet reference (reference)'],['../md_docs_2reference_2ra8p1__vs__ra8d2.html',1,'RA8P1 vs RA8D2 &amp;ndash; durable difference reference']]],
  ['reference_20reference_22',['Datasheet reference (reference)',['../ra8_docsub_reference.html',1,'ra8_docs']]],
  ['regen_20script_20auto_20classification_23',['ADR-0004: DO-178C 6.4.4.3 deactivated-condition policy with regen-script auto-classification',['../md_docs_2adr_20004-deactivated-condition-policy.html',1,'ra8_docsub_adr']]],
  ['register_24',['MISRA-C 2012 Deviation Register',['../md_docs_2qualification_2MISRA__DEVIATIONS.html',1,'ra8_docsub_qualification']]],
  ['renesas_20only_20not_20shipped_25',['Vendor Blobs (Renesas-Only, Not Shipped)',['../md_docs_2VENDOR__BLOBS.html',1,'ra8_docs']]],
  ['report_20ek_20ra8d2_20v1_26',['Hardware Bring-up Report (EK-RA8D2 v1)',['../md_docs_2HARDWARE__BRINGUP.html',1,'ra8_docs']]],
  ['requirements_20specification_20srs_27',['Software Requirements Specification (SRS)',['../md_docs_2qualification_2SRS.html',1,'ra8_docsub_qualification']]],
  ['results_20svr_28',['Software Verification Results (SVR)',['../md_docs_2qualification_2SVR.html',1,'ra8_docsub_qualification']]],
  ['ring_20and_20world_20tagging_29',['Ring and World tagging',['../md_docs_2RING__AND__WORLD.html',1,'ra8_docs']]],
  ['root_20of_20trust_20signed_20image_20trailer_30',['ROT1 &amp;ndash; The Root-of-Trust Signed-Image Trailer',['../md_docs_2formats_2ROT1.html',1,'ra8_docsub_formats']]],
  ['root_20of_20trust_20signing_20key_31',['Root-of-Trust Signing Key',['../md_docs_2ROOT__OF__TRUST.html',1,'ra8_docs']]],
  ['rot_20header_32',['NSR1 &amp;ndash; The Non-Secure Image RoT Header',['../md_docs_2formats_2NSR1.html',1,'ra8_docsub_formats']]],
  ['rot1_20ndash_20the_20root_20of_20trust_20signed_20image_20trailer_33',['ROT1 &amp;ndash; The Root-of-Trust Signed-Image Trailer',['../md_docs_2formats_2ROT1.html',1,'ra8_docsub_formats']]],
  ['ruy_20profiler_20instrumentation_20stub_34',['SOUP Justification: ruy (profiler instrumentation stub)',['../md_docs_2SOUP_2ruy.html',1,'ra8_docsub_SOUP']]]
];
