var searchData=
[
  ['c_202012_20compliance_0',['MISRA-C 2012 Compliance',['../md_docs_2MISRA.html',1,'ra8_docs']]],
  ['c_202012_20deviation_20register_1',['MISRA-C 2012 Deviation Register',['../md_docs_2qualification_2MISRA__DEVIATIONS.html',1,'ra8_docsub_qualification']]],
  ['c6_2',['C6',['../ra8_ex_ek_ra8d2_hw_pending_c6.html',1,'ra8_ex_ek_ra8d2_hw_pending']]],
  ['c6_20companion_20radio_20just_20hil_3a_3ac6_3',['ESP32-C6 companion radio (just hil::c6)',['../ra8_ex_ek_ra8d2_hw_validated_c6.html',1,'ra8_ex_ek_ra8d2_hw_validated']]],
  ['c6_20wireless_20co_20processor_20architecture_4',['ESP32-C6 wireless co-processor architecture',['../md_docs_2design_2c6__wireless__architecture.html',1,'ra8_docsub_design']]],
  ['cases_20procedures_20svcp_5',['Software Verification Cases &amp;amp; Procedures (SVCP)',['../md_docs_2qualification_2SVCP.html',1,'ra8_docsub_qualification']]],
  ['catalog_6',['MC/DC Deactivated-Decision Catalog',['../md_docs_2MCDC__DEACTIVATIONS.html',1,'ra8_docs']]],
  ['certification_20psac_7',['Plan for Software Aspects of Certification (PSAC)',['../md_docs_2qualification_2PSAC.html',1,'ra8_docsub_qualification']]],
  ['certification_20scope_8',['Certification Scope',['../md_docs_2CERTIFICATION__SCOPE.html',1,'ra8_docs']]],
  ['chapter_20map_9',['RA8D2 Hardware User&apos;s Manual &amp;ndash; Chapter Map',['../md_docs_2reference_2CHAPTER__MAP.html',1,'ra8_docsub_reference']]],
  ['chunked_20rabook_20container_10',['RBKC &amp;ndash; The Chunked &lt;span class=&quot;tt&quot;&gt;.rabook&lt;/span&gt; Container',['../md_docs_2formats_2RBKC.html',1,'ra8_docsub_formats']]],
  ['ci_20fleet_3a_20declared_20tuned_20and_20scheduled_11',['The CI fleet: declared, tuned, and scheduled',['../md_docs_2CI__FLEET.html',1,'ra8_docs']]],
  ['citation_20policy_12',['Citation Policy',['../md_docs_2CITATION__POLICY.html',1,'ra8_docs']]],
  ['clang_20static_20analyzer_20scan_20build_13',['Static Analysis: Clang Static Analyzer (scan-build)',['../md_docs_2STATIC__ANALYSIS.html',1,'ra8_docs']]],
  ['classification_14',['ADR-0004: DO-178C 6.4.4.3 deactivated-condition policy with regen-script auto-classification',['../md_docs_2adr_20004-deactivated-condition-policy.html',1,'ra8_docsub_adr']]],
  ['co_20processor_20architecture_15',['ESP32-C6 wireless co-processor architecture',['../md_docs_2design_2c6__wireless__architecture.html',1,'ra8_docsub_design']]],
  ['co_20processor_20firmware_16',['SOUP Justification: Espressif esp-hosted-mcu (co-processor firmware)',['../md_docs_2SOUP_2esp-hosted.html',1,'ra8_docsub_SOUP']]],
  ['companion_20radio_20just_20hil_3a_3ac6_17',['ESP32-C6 companion radio (just hil::c6)',['../ra8_ex_ek_ra8d2_hw_validated_c6.html',1,'ra8_ex_ek_ra8d2_hw_validated']]],
  ['completion_20record_20historical_18',['HAL Completion Record (Historical)',['../md_docs_2ROADMAP.html',1,'ra8_docs']]],
  ['compliance_19',['MISRA-C 2012 Compliance',['../md_docs_2MISRA.html',1,'ra8_docs']]],
  ['component_20justifications_20soup_20',['SOUP component justifications (SOUP)',['../ra8_docsub_SOUP.html',1,'ra8_docs']]],
  ['condition_20policy_20with_20regen_20script_20auto_20classification_21',['ADR-0004: DO-178C 6.4.4.3 deactivated-condition policy with regen-script auto-classification',['../md_docs_2adr_20004-deactivated-condition-policy.html',1,'ra8_docsub_adr']]],
  ['configuration_20management_20plan_20scmp_22',['Software Configuration Management Plan (SCMP)',['../md_docs_2qualification_2SCMP.html',1,'ra8_docsub_qualification']]],
  ['conformance_20subset_23',['EPUB Reader &amp;ndash; Supported Conformance Subset',['../md_docs_2EPUB__CONFORMANCE.html',1,'ra8_docs']]],
  ['container_24',['Container',['../md_docs_2formats_2NPU1.html',1,'NPU1 &amp;ndash; The &lt;tt&gt;.npub&lt;/tt&gt; Ethos-U55 Model Container'],['../md_docs_2formats_2RBKC.html',1,'RBKC &amp;ndash; The Chunked &lt;tt&gt;.rabook&lt;/tt&gt; Container']]],
  ['content_20licensing_25',['E-Book Content Licensing',['../md_docs_2CONTENT__LICENSING.html',1,'ra8_docs']]],
  ['contracts_26',['RA8_* Annotation Contracts',['../md_docs_2ANNOTATIONS.html',1,'ra8_docs']]],
  ['core_20cpu0_20cpu1_20on_20the_20ra8d2_27',['Dual-core (CPU0 / CPU1) on the RA8D2',['../md_docs_2DUAL__CORE.html',1,'ra8_docs']]],
  ['coverage_20do_20178c_20level_20b_28',['MC/DC Coverage (DO-178C Level B)',['../md_docs_2MCDC.html',1,'ra8_docs']]],
  ['coverage_20gap_20audit_29',['MC/DC Coverage Gap Audit',['../md_docs_2MCDC__GAPS.html',1,'ra8_docs']]],
  ['coverage_20statement_20branch_30',['Coverage (statement + branch)',['../md_docs_2COVERAGE.html',1,'ra8_docs']]],
  ['cppcheck_20only_20misra_20enforcement_20under_20a_20foss_20only_20budget_31',['ADR-0002: cppcheck-only MISRA enforcement under a FOSS-only budget',['../md_docs_2adr_20002-cppcheck-only-misra-enforcement.html',1,'ra8_docsub_adr']]],
  ['cpu0_20cpu1_20on_20the_20ra8d2_32',['Dual-core (CPU0 / CPU1) on the RA8D2',['../md_docs_2DUAL__CORE.html',1,'ra8_docs']]],
  ['cpu1_20on_20the_20ra8d2_33',['Dual-core (CPU0 / CPU1) on the RA8D2',['../md_docs_2DUAL__CORE.html',1,'ra8_docs']]],
  ['crypto_34',['SOUP Justification: TF-PSA-Crypto',['../md_docs_2SOUP_2tf-psa-crypto.html',1,'ra8_docsub_SOUP']]]
];
