var searchData=
[
  ['tagging_0',['Ring and World tagging',['../md_docs_2RING__AND__WORLD.html',1,'ra8_docs']]],
  ['target_1',['ADR-0001: Adopt IEC 61508 SIL 3 / DO-178C Level B as the qualification target',['../md_docs_2adr_20001-iec-61508-sil-3-do-178c-level-b-target.html',1,'ra8_docsub_adr']]],
  ['tensorflow_20lite_20for_20microcontrollers_2',['SOUP Justification: TensorFlow Lite for Microcontrollers',['../md_docs_2SOUP_2tflite-micro.html',1,'ra8_docsub_SOUP']]],
  ['test_20only_20access_20to_20internal_20symbols_20via_20lt_20module_20gt_20_5finternal_20h_3',['ADR-0003: Test-only access to internal symbols via &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_internal.h&lt;/span&gt;',['../md_docs_2adr_20003-test-only-internal-headers.html',1,'ra8_docsub_adr']]],
  ['tf_20psa_20crypto_4',['SOUP Justification: TF-PSA-Crypto',['../md_docs_2SOUP_2tf-psa-crypto.html',1,'ra8_docsub_SOUP']]],
  ['the_20chunked_20rabook_20container_5',['RBKC &amp;ndash; The Chunked &lt;span class=&quot;tt&quot;&gt;.rabook&lt;/span&gt; Container',['../md_docs_2formats_2RBKC.html',1,'ra8_docsub_formats']]],
  ['the_20ci_20fleet_3a_20declared_20tuned_20and_20scheduled_6',['The CI fleet: declared, tuned, and scheduled',['../md_docs_2CI__FLEET.html',1,'ra8_docs']]],
  ['the_20ek_20ra8d2_7',['Debugging the EK-RA8D2',['../md_docs_2DEBUG.html',1,'ra8_docs']]],
  ['the_20jump_20offset_20band_20tile_20atlas_8',['JOF &amp;ndash; The Jump-Offset Band-Tile Atlas',['../md_docs_2formats_2JOF.html',1,'ra8_docsub_formats']]],
  ['the_20loop_20hil_9',['Hardware-in-the-loop (HIL)',['../ra8_ex_ek_ra8d2_hw_validated_hil.html',1,'ra8_ex_ek_ra8d2_hw_validated']]],
  ['the_20loop_20hil_20developer_20workflow_10',['Hardware-in-the-Loop (HIL) Developer Workflow',['../md_docs_2HIL__DEVELOPER__WORKFLOW.html',1,'ra8_docs']]],
  ['the_20non_20secure_20image_20rot_20header_11',['NSR1 &amp;ndash; The Non-Secure Image RoT Header',['../md_docs_2formats_2NSR1.html',1,'ra8_docsub_formats']]],
  ['the_20npub_20ethos_20u55_20model_20container_12',['NPU1 &amp;ndash; The &lt;span class=&quot;tt&quot;&gt;.npub&lt;/span&gt; Ethos-U55 Model Container',['../md_docs_2formats_2NPU1.html',1,'ra8_docsub_formats']]],
  ['the_20qualification_20target_13',['ADR-0001: Adopt IEC 61508 SIL 3 / DO-178C Level B as the qualification target',['../md_docs_2adr_20001-iec-61508-sil-3-do-178c-level-b-target.html',1,'ra8_docsub_adr']]],
  ['the_20ra8d2_14',['Dual-core (CPU0 / CPU1) on the RA8D2',['../md_docs_2DUAL__CORE.html',1,'ra8_docs']]],
  ['the_20root_20of_20trust_20signed_20image_20trailer_15',['ROT1 &amp;ndash; The Root-of-Trust Signed-Image Trailer',['../md_docs_2formats_2ROT1.html',1,'ra8_docsub_formats']]],
  ['threadx_16',['SOUP Justification: Eclipse ThreadX',['../md_docs_2SOUP_2threadx.html',1,'ra8_docsub_SOUP']]],
  ['tile_20atlas_17',['JOF &amp;ndash; The Jump-Offset Band-Tile Atlas',['../md_docs_2formats_2JOF.html',1,'ra8_docsub_formats']]],
  ['tls_18',['SOUP Justification: Mbed TLS',['../md_docs_2SOUP_2mbedtls.html',1,'ra8_docsub_SOUP']]],
  ['to_20internal_20symbols_20via_20lt_20module_20gt_20_5finternal_20h_19',['ADR-0003: Test-only access to internal symbols via &lt;span class=&quot;tt&quot;&gt;&amp;lt;module&amp;gt;_internal.h&lt;/span&gt;',['../md_docs_2adr_20003-test-only-internal-headers.html',1,'ra8_docsub_adr']]],
  ['tool_20',['SOUP Justification: Arm Ethos-U Vela (host build tool)',['../md_docs_2SOUP_2vela.html',1,'ra8_docsub_SOUP']]],
  ['tool_20qualification_20dossier_21',['Tool Qualification Dossier',['../md_docs_2qualification_2TOOL__QUALIFICATION.html',1,'ra8_docsub_qualification']]],
  ['toolchain_22',['TOOLCHAIN',['../md_docs_2TOOLCHAIN.html',1,'ra8_docs']]],
  ['tour_20libs_23',['Module tour (&lt;span class=&quot;tt&quot;&gt;libs/&lt;/span&gt;)',['../md_docs_2MODULES.html',1,'ra8_docs']]],
  ['trailer_24',['ROT1 &amp;ndash; The Root-of-Trust Signed-Image Trailer',['../md_docs_2formats_2ROT1.html',1,'ra8_docsub_formats']]],
  ['transports_20not_20designs_25',['One update pipeline: OTA and USB are transports, not designs',['../md_docs_2design_2c6__update__pipeline.html',1,'ra8_docsub_design']]],
  ['truetype_26',['SOUP Justification: stb (image / truetype)',['../md_docs_2SOUP_2stb.html',1,'ra8_docsub_SOUP']]],
  ['trust_20signed_20image_20trailer_27',['ROT1 &amp;ndash; The Root-of-Trust Signed-Image Trailer',['../md_docs_2formats_2ROT1.html',1,'ra8_docsub_formats']]],
  ['trust_20signing_20key_28',['Root-of-Trust Signing Key',['../md_docs_2ROOT__OF__TRUST.html',1,'ra8_docs']]],
  ['tuned_20and_20scheduled_29',['The CI fleet: declared, tuned, and scheduled',['../md_docs_2CI__FLEET.html',1,'ra8_docs']]]
];
