var searchData=
[
  ['datasheet_20reference_20reference_0',['Datasheet reference (reference)',['../ra8_docsub_reference.html',1,'ra8_docs']]],
  ['dc_20coverage_20do_20178c_20level_20b_1',['MC/DC Coverage (DO-178C Level B)',['../md_docs_2MCDC.html',1,'ra8_docs']]],
  ['dc_20coverage_20gap_20audit_2',['MC/DC Coverage Gap Audit',['../md_docs_2MCDC__GAPS.html',1,'ra8_docs']]],
  ['dc_20deactivated_20condition_20catalog_3',['MC/DC Deactivated-Condition Catalog',['../md_docs_2MCDC__DEACTIVATIONS.html',1,'ra8_docs']]],
  ['deactivated_20condition_20catalog_4',['MC/DC Deactivated-Condition Catalog',['../md_docs_2MCDC__DEACTIVATIONS.html',1,'ra8_docs']]],
  ['deactivated_20condition_20policy_20with_20regen_20script_20auto_20classification_5',['ADR-0004: DO-178C 6.4.4.3 deactivated-condition policy with regen-script auto-classification',['../md_docs_2adr_20004-deactivated-condition-policy.html',1,'ra8_docsub_adr']]],
  ['debugging_20the_20ek_20ra8d2_6',['Debugging the EK-RA8D2',['../md_docs_2DEBUG.html',1,'ra8_docs']]],
  ['decision_20records_20adr_7',['Architecture Decision Records (adr)',['../ra8_docsub_adr.html',1,'ra8_docs']]],
  ['declared_20tuned_20and_20scheduled_8',['The CI fleet: declared, tuned, and scheduled',['../md_docs_2CI__FLEET.html',1,'ra8_docs']]],
  ['decode_20only_9',['SOUP Justification: XZ Embedded (decode-only)',['../md_docs_2SOUP_2xz__embedded.html',1,'ra8_docsub_SOUP']]],
  ['decoder_10',['SOUP Justification: libwebp (WebP decoder)',['../md_docs_2SOUP_2libwebp.html',1,'ra8_docsub_SOUP']]],
  ['deprecated_11',['Hardware-in-the-Loop CI Runner Setup (EK-RA8D2) &amp;ndash; DEPRECATED',['../md_docs_2qualification_2HW__IN__LOOP__RUNNER.html',1,'ra8_docsub_qualification']]],
  ['description_20sdd_12',['Software Design Description (SDD)',['../md_docs_2qualification_2SDD.html',1,'ra8_docsub_qualification']]],
  ['design_13',['Design',['../ra8_docsub_design.html',1,'ra8_docs']]],
  ['design_20description_20sdd_14',['Software Design Description (SDD)',['../md_docs_2qualification_2SDD.html',1,'ra8_docsub_qualification']]],
  ['designs_15',['One update pipeline: OTA and USB are transports, not designs',['../md_docs_2design_2c6__update__pipeline.html',1,'ra8_docsub_design']]],
  ['developer_20workflow_16',['Hardware-in-the-Loop (HIL) Developer Workflow',['../md_docs_2HIL__DEVELOPER__WORKFLOW.html',1,'ra8_docs']]],
  ['development_20plan_20sdp_17',['Software Development Plan (SDP)',['../md_docs_2qualification_2SDP.html',1,'ra8_docsub_qualification']]],
  ['deviation_20register_18',['MISRA-C 2012 Deviation Register',['../md_docs_2qualification_2MISRA__DEVIATIONS.html',1,'ra8_docsub_qualification']]],
  ['difference_20analysis_20multi_20chip_20plan_19',['RA8D2 vs RA8P1 &amp;ndash; difference analysis + multi-chip plan',['../md_docs_2RA8D2__VS__RA8P1.html',1,'ra8_docs']]],
  ['difference_20reference_20',['RA8P1 vs RA8D2 &amp;ndash; durable difference reference',['../md_docs_2reference_2ra8p1__vs__ra8d2.html',1,'ra8_docsub_reference']]],
  ['do_20178c_206_204_204_203_20deactivated_20condition_20policy_20with_20regen_20script_20auto_20classification_21',['ADR-0004: DO-178C 6.4.4.3 deactivated-condition policy with regen-script auto-classification',['../md_docs_2adr_20004-deactivated-condition-policy.html',1,'ra8_docsub_adr']]],
  ['do_20178c_20level_20b_22',['DO 178C Level B',['../md_docs_2MCDC.html',1,'MC/DC Coverage (DO-178C Level B)'],['../md_docs_2QUALIFICATION__ROADMAP.html',1,'Qualification Roadmap &amp;ndash; IEC 61508 SIL 3 / DO-178C Level B']]],
  ['do_20178c_20level_20b_20as_20the_20qualification_20target_23',['ADR-0001: Adopt IEC 61508 SIL 3 / DO-178C Level B as the qualification target',['../md_docs_2adr_20001-iec-61508-sil-3-do-178c-level-b-target.html',1,'ra8_docsub_adr']]],
  ['documentation_24',['Documentation',['../ra8_docs.html',1,'Documentation'],['../md_docs_2DOCS.html',1,'Doxygen HTML Documentation']]],
  ['documentation_20gap_20report_25',['Doxygen Documentation Gap Report',['../md_docs_2DOXYGEN__GAPS.html',1,'ra8_docs']]],
  ['dossier_26',['Tool Qualification Dossier',['../md_docs_2qualification_2TOOL__QUALIFICATION.html',1,'ra8_docsub_qualification']]],
  ['doxygen_20documentation_20gap_20report_27',['Doxygen Documentation Gap Report',['../md_docs_2DOXYGEN__GAPS.html',1,'ra8_docs']]],
  ['doxygen_20html_20documentation_28',['Doxygen HTML Documentation',['../md_docs_2DOCS.html',1,'ra8_docs']]],
  ['driver_29',['SOUP Justification: Espressif esp-hosted-mcu (host driver)',['../md_docs_2SOUP_2esp-hosted-host.html',1,'ra8_docsub_SOUP']]],
  ['driver_20status_20matrix_30',['Driver Status Matrix',['../md_docs_2DRIVER__STATUS.html',1,'ra8_docs']]],
  ['dual_20core_20cpu0_20cpu1_20on_20the_20ra8d2_31',['Dual-core (CPU0 / CPU1) on the RA8D2',['../md_docs_2DUAL__CORE.html',1,'ra8_docs']]],
  ['duo_32',['SOUP Justification: Eclipse NetX Duo',['../md_docs_2SOUP_2netxduo.html',1,'ra8_docsub_SOUP']]],
  ['durable_20difference_20reference_33',['RA8P1 vs RA8D2 &amp;ndash; durable difference reference',['../md_docs_2reference_2ra8p1__vs__ra8d2.html',1,'ra8_docsub_reference']]]
];
