/**
 * @file ra8_media_download.pb-c.c
 * @brief Generated protobuf-C implementation of the media-download protocol.
 *
 * @details
 * Generated from `ra8_media_download.proto` by the pinned protobuf-C compiler.
 * Do not edit this file directly; use `scripts/gen/gen_ra8_media_proto.sh` so
 * the checked-in codec and its attribution remain reproducible.
 *
 * @copyright Copyright (c) 2026 Brighton Sikarskie
 * SPDX-License-Identifier: MIT
 */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ra8_media_download.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ra8_media_download.pb-c.h"
void   ra8__mdl__start_request__init
                     (Ra8__Mdl__StartRequest         *message)
{
  static const Ra8__Mdl__StartRequest init_value = RA8__MDL__START_REQUEST__INIT;
  *message = init_value;
}
size_t ra8__mdl__start_request__get_packed_size
                     (const Ra8__Mdl__StartRequest *message)
{
  assert(message->base.descriptor == &ra8__mdl__start_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ra8__mdl__start_request__pack
                     (const Ra8__Mdl__StartRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ra8__mdl__start_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ra8__mdl__start_request__pack_to_buffer
                     (const Ra8__Mdl__StartRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ra8__mdl__start_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ra8__Mdl__StartRequest *
       ra8__mdl__start_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ra8__Mdl__StartRequest *)
     protobuf_c_message_unpack (&ra8__mdl__start_request__descriptor,
                                allocator, len, data);
}
void   ra8__mdl__start_request__free_unpacked
                     (Ra8__Mdl__StartRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ra8__mdl__start_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ra8__mdl__accepted__init
                     (Ra8__Mdl__Accepted         *message)
{
  static const Ra8__Mdl__Accepted init_value = RA8__MDL__ACCEPTED__INIT;
  *message = init_value;
}
size_t ra8__mdl__accepted__get_packed_size
                     (const Ra8__Mdl__Accepted *message)
{
  assert(message->base.descriptor == &ra8__mdl__accepted__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ra8__mdl__accepted__pack
                     (const Ra8__Mdl__Accepted *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ra8__mdl__accepted__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ra8__mdl__accepted__pack_to_buffer
                     (const Ra8__Mdl__Accepted *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ra8__mdl__accepted__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ra8__Mdl__Accepted *
       ra8__mdl__accepted__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ra8__Mdl__Accepted *)
     protobuf_c_message_unpack (&ra8__mdl__accepted__descriptor,
                                allocator, len, data);
}
void   ra8__mdl__accepted__free_unpacked
                     (Ra8__Mdl__Accepted *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ra8__mdl__accepted__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ra8__mdl__next_request__init
                     (Ra8__Mdl__NextRequest         *message)
{
  static const Ra8__Mdl__NextRequest init_value = RA8__MDL__NEXT_REQUEST__INIT;
  *message = init_value;
}
size_t ra8__mdl__next_request__get_packed_size
                     (const Ra8__Mdl__NextRequest *message)
{
  assert(message->base.descriptor == &ra8__mdl__next_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ra8__mdl__next_request__pack
                     (const Ra8__Mdl__NextRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ra8__mdl__next_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ra8__mdl__next_request__pack_to_buffer
                     (const Ra8__Mdl__NextRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ra8__mdl__next_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ra8__Mdl__NextRequest *
       ra8__mdl__next_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ra8__Mdl__NextRequest *)
     protobuf_c_message_unpack (&ra8__mdl__next_request__descriptor,
                                allocator, len, data);
}
void   ra8__mdl__next_request__free_unpacked
                     (Ra8__Mdl__NextRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ra8__mdl__next_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ra8__mdl__chunk__init
                     (Ra8__Mdl__Chunk         *message)
{
  static const Ra8__Mdl__Chunk init_value = RA8__MDL__CHUNK__INIT;
  *message = init_value;
}
size_t ra8__mdl__chunk__get_packed_size
                     (const Ra8__Mdl__Chunk *message)
{
  assert(message->base.descriptor == &ra8__mdl__chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ra8__mdl__chunk__pack
                     (const Ra8__Mdl__Chunk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ra8__mdl__chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ra8__mdl__chunk__pack_to_buffer
                     (const Ra8__Mdl__Chunk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ra8__mdl__chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ra8__Mdl__Chunk *
       ra8__mdl__chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ra8__Mdl__Chunk *)
     protobuf_c_message_unpack (&ra8__mdl__chunk__descriptor,
                                allocator, len, data);
}
void   ra8__mdl__chunk__free_unpacked
                     (Ra8__Mdl__Chunk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ra8__mdl__chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ra8__mdl__cancel_request__init
                     (Ra8__Mdl__CancelRequest         *message)
{
  static const Ra8__Mdl__CancelRequest init_value = RA8__MDL__CANCEL_REQUEST__INIT;
  *message = init_value;
}
size_t ra8__mdl__cancel_request__get_packed_size
                     (const Ra8__Mdl__CancelRequest *message)
{
  assert(message->base.descriptor == &ra8__mdl__cancel_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ra8__mdl__cancel_request__pack
                     (const Ra8__Mdl__CancelRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ra8__mdl__cancel_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ra8__mdl__cancel_request__pack_to_buffer
                     (const Ra8__Mdl__CancelRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ra8__mdl__cancel_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ra8__Mdl__CancelRequest *
       ra8__mdl__cancel_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ra8__Mdl__CancelRequest *)
     protobuf_c_message_unpack (&ra8__mdl__cancel_request__descriptor,
                                allocator, len, data);
}
void   ra8__mdl__cancel_request__free_unpacked
                     (Ra8__Mdl__CancelRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ra8__mdl__cancel_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ra8__mdl__cancelled__init
                     (Ra8__Mdl__Cancelled         *message)
{
  static const Ra8__Mdl__Cancelled init_value = RA8__MDL__CANCELLED__INIT;
  *message = init_value;
}
size_t ra8__mdl__cancelled__get_packed_size
                     (const Ra8__Mdl__Cancelled *message)
{
  assert(message->base.descriptor == &ra8__mdl__cancelled__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ra8__mdl__cancelled__pack
                     (const Ra8__Mdl__Cancelled *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ra8__mdl__cancelled__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ra8__mdl__cancelled__pack_to_buffer
                     (const Ra8__Mdl__Cancelled *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ra8__mdl__cancelled__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ra8__Mdl__Cancelled *
       ra8__mdl__cancelled__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ra8__Mdl__Cancelled *)
     protobuf_c_message_unpack (&ra8__mdl__cancelled__descriptor,
                                allocator, len, data);
}
void   ra8__mdl__cancelled__free_unpacked
                     (Ra8__Mdl__Cancelled *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ra8__mdl__cancelled__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ra8__mdl__start_request__field_descriptors[3] =
{
  {
    "protocol_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__StartRequest, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__StartRequest, url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "format",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__StartRequest, format),
    &ra8__mdl__format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ra8__mdl__start_request__field_indices_by_name[] = {
  2,   /* field[2] = format */
  0,   /* field[0] = protocol_version */
  1,   /* field[1] = url */
};
static const ProtobufCIntRange ra8__mdl__start_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ra8__mdl__start_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ra8.mdl.StartRequest",
  "StartRequest",
  "Ra8__Mdl__StartRequest",
  "ra8.mdl",
  sizeof(Ra8__Mdl__StartRequest),
  3,
  ra8__mdl__start_request__field_descriptors,
  ra8__mdl__start_request__field_indices_by_name,
  1,  ra8__mdl__start_request__number_ranges,
  (ProtobufCMessageInit) ra8__mdl__start_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ra8__mdl__accepted__field_descriptors[4] =
{
  {
    "protocol_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Accepted, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Accepted, job_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_chunk_bytes",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Accepted, max_chunk_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "format",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Accepted, format),
    &ra8__mdl__format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ra8__mdl__accepted__field_indices_by_name[] = {
  3,   /* field[3] = format */
  1,   /* field[1] = job_id */
  2,   /* field[2] = max_chunk_bytes */
  0,   /* field[0] = protocol_version */
};
static const ProtobufCIntRange ra8__mdl__accepted__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ra8__mdl__accepted__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ra8.mdl.Accepted",
  "Accepted",
  "Ra8__Mdl__Accepted",
  "ra8.mdl",
  sizeof(Ra8__Mdl__Accepted),
  4,
  ra8__mdl__accepted__field_descriptors,
  ra8__mdl__accepted__field_indices_by_name,
  1,  ra8__mdl__accepted__number_ranges,
  (ProtobufCMessageInit) ra8__mdl__accepted__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ra8__mdl__next_request__field_descriptors[4] =
{
  {
    "protocol_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__NextRequest, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__NextRequest, job_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acknowledged_offset",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__NextRequest, acknowledged_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_bytes",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__NextRequest, max_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ra8__mdl__next_request__field_indices_by_name[] = {
  2,   /* field[2] = acknowledged_offset */
  1,   /* field[1] = job_id */
  3,   /* field[3] = max_bytes */
  0,   /* field[0] = protocol_version */
};
static const ProtobufCIntRange ra8__mdl__next_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ra8__mdl__next_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ra8.mdl.NextRequest",
  "NextRequest",
  "Ra8__Mdl__NextRequest",
  "ra8.mdl",
  sizeof(Ra8__Mdl__NextRequest),
  4,
  ra8__mdl__next_request__field_descriptors,
  ra8__mdl__next_request__field_indices_by_name,
  1,  ra8__mdl__next_request__number_ranges,
  (ProtobufCMessageInit) ra8__mdl__next_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ra8__mdl__chunk__field_descriptors[9] =
{
  {
    "protocol_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, job_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_bytes",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, total_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, state),
    &ra8__mdl__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha256",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Chunk, sha256),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ra8__mdl__chunk__field_indices_by_name[] = {
  4,   /* field[4] = data */
  1,   /* field[1] = job_id */
  3,   /* field[3] = offset */
  0,   /* field[0] = protocol_version */
  2,   /* field[2] = sequence */
  8,   /* field[8] = sha256 */
  6,   /* field[6] = state */
  7,   /* field[7] = status */
  5,   /* field[5] = total_bytes */
};
static const ProtobufCIntRange ra8__mdl__chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor ra8__mdl__chunk__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ra8.mdl.Chunk",
  "Chunk",
  "Ra8__Mdl__Chunk",
  "ra8.mdl",
  sizeof(Ra8__Mdl__Chunk),
  9,
  ra8__mdl__chunk__field_descriptors,
  ra8__mdl__chunk__field_indices_by_name,
  1,  ra8__mdl__chunk__number_ranges,
  (ProtobufCMessageInit) ra8__mdl__chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ra8__mdl__cancel_request__field_descriptors[2] =
{
  {
    "protocol_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__CancelRequest, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__CancelRequest, job_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ra8__mdl__cancel_request__field_indices_by_name[] = {
  1,   /* field[1] = job_id */
  0,   /* field[0] = protocol_version */
};
static const ProtobufCIntRange ra8__mdl__cancel_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ra8__mdl__cancel_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ra8.mdl.CancelRequest",
  "CancelRequest",
  "Ra8__Mdl__CancelRequest",
  "ra8.mdl",
  sizeof(Ra8__Mdl__CancelRequest),
  2,
  ra8__mdl__cancel_request__field_descriptors,
  ra8__mdl__cancel_request__field_indices_by_name,
  1,  ra8__mdl__cancel_request__number_ranges,
  (ProtobufCMessageInit) ra8__mdl__cancel_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ra8__mdl__cancelled__field_descriptors[3] =
{
  {
    "protocol_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Cancelled, protocol_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "job_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Cancelled, job_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ra8__Mdl__Cancelled, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ra8__mdl__cancelled__field_indices_by_name[] = {
  1,   /* field[1] = job_id */
  0,   /* field[0] = protocol_version */
  2,   /* field[2] = status */
};
static const ProtobufCIntRange ra8__mdl__cancelled__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ra8__mdl__cancelled__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ra8.mdl.Cancelled",
  "Cancelled",
  "Ra8__Mdl__Cancelled",
  "ra8.mdl",
  sizeof(Ra8__Mdl__Cancelled),
  3,
  ra8__mdl__cancelled__field_descriptors,
  ra8__mdl__cancelled__field_indices_by_name,
  1,  ra8__mdl__cancelled__number_ranges,
  (ProtobufCMessageInit) ra8__mdl__cancelled__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ra8__mdl__format__enum_values_by_number[10] =
{
  { "FORMAT_LOOSE", "RA8__MDL__FORMAT__FORMAT_LOOSE", 0 },
  { "FORMAT_CBZ", "RA8__MDL__FORMAT__FORMAT_CBZ", 1 },
  { "FORMAT_CBT", "RA8__MDL__FORMAT__FORMAT_CBT", 2 },
  { "FORMAT_CBR", "RA8__MDL__FORMAT__FORMAT_CBR", 3 },
  { "FORMAT_CBT_XZ", "RA8__MDL__FORMAT__FORMAT_CBT_XZ", 4 },
  { "FORMAT_CBT_GZ", "RA8__MDL__FORMAT__FORMAT_CBT_GZ", 5 },
  { "FORMAT_EPUB", "RA8__MDL__FORMAT__FORMAT_EPUB", 6 },
  { "FORMAT_JOF", "RA8__MDL__FORMAT__FORMAT_JOF", 7 },
  { "FORMAT_RABOOK", "RA8__MDL__FORMAT__FORMAT_RABOOK", 8 },
  { "FORMAT_INVALID", "RA8__MDL__FORMAT__FORMAT_INVALID", 255 },
};
static const ProtobufCIntRange ra8__mdl__format__value_ranges[] = {
{0, 0},{255, 9},{0, 10}
};
static const ProtobufCEnumValueIndex ra8__mdl__format__enum_values_by_name[10] =
{
  { "FORMAT_CBR", 3 },
  { "FORMAT_CBT", 2 },
  { "FORMAT_CBT_GZ", 5 },
  { "FORMAT_CBT_XZ", 4 },
  { "FORMAT_CBZ", 1 },
  { "FORMAT_EPUB", 6 },
  { "FORMAT_INVALID", 9 },
  { "FORMAT_JOF", 7 },
  { "FORMAT_LOOSE", 0 },
  { "FORMAT_RABOOK", 8 },
};
const ProtobufCEnumDescriptor ra8__mdl__format__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ra8.mdl.Format",
  "Format",
  "Ra8__Mdl__Format",
  "ra8.mdl",
  10,
  ra8__mdl__format__enum_values_by_number,
  10,
  ra8__mdl__format__enum_values_by_name,
  2,
  ra8__mdl__format__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ra8__mdl__state__enum_values_by_number[6] =
{
  { "STATE_UNSPECIFIED", "RA8__MDL__STATE__STATE_UNSPECIFIED", 0 },
  { "STATE_ACCEPTED", "RA8__MDL__STATE__STATE_ACCEPTED", 1 },
  { "STATE_DOWNLOADING", "RA8__MDL__STATE__STATE_DOWNLOADING", 2 },
  { "STATE_COMPLETE", "RA8__MDL__STATE__STATE_COMPLETE", 3 },
  { "STATE_CANCELLED", "RA8__MDL__STATE__STATE_CANCELLED", 4 },
  { "STATE_FAILED", "RA8__MDL__STATE__STATE_FAILED", 5 },
};
static const ProtobufCIntRange ra8__mdl__state__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ra8__mdl__state__enum_values_by_name[6] =
{
  { "STATE_ACCEPTED", 1 },
  { "STATE_CANCELLED", 4 },
  { "STATE_COMPLETE", 3 },
  { "STATE_DOWNLOADING", 2 },
  { "STATE_FAILED", 5 },
  { "STATE_UNSPECIFIED", 0 },
};
const ProtobufCEnumDescriptor ra8__mdl__state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ra8.mdl.State",
  "State",
  "Ra8__Mdl__State",
  "ra8.mdl",
  6,
  ra8__mdl__state__enum_values_by_number,
  6,
  ra8__mdl__state__enum_values_by_name,
  1,
  ra8__mdl__state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
