/**
 * @file test_unarch_xz.c
 * @brief Tests for the bounded XZ decoder wrapper (unarch_xz + pool + io).
 *
 * @details
 * Drives the XZ leg of the archive-hardening subsystem over committed real
 * `.xz` fixtures (tests/inc/unarch_xz_fixture.h, generated by
 * scripts/gen/gen_unarch_xz_fixture.py) and hostile variants derived from
 * them in-place:
 *
 *   1. honest streams (CRC64 default and CRC32) decode byte-exactly through
 *      the multi-pass unwrap loop,
 *   2. every hostile shape is rejected fail-closed with the specific error:
 *      SHA-256 check (unsupported), 8 MiB declared dictionary (over the
 *      scratch budget), corruption, truncation, trailing bytes, a non-XZ
 *      buffer, and a 3690:1 zeros bomb that breaches the DEFAULT policy's
 *      ratio bound mid-decode,
 *   3. the tightened-policy axes each fire (output cap, iteration budget),
 *   4. the zero-heap pool arena and the flat-memory read seam behave at
 *      every edge (alignment, exhaustion, double-install, clamping).
 *
 * @copyright Copyright (c) 2026 Brighton Sikarskie
 * SPDX-License-Identifier: MIT
 */

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "ra8_attributes.h"
#include "ra8_decomp_limits.h"
#include "ra8_err.h"
#include "unarch_io.h"
#include "unarch_xz.h"
#include "unarch_xz_fixture.h"
#include "unarch_xz_pool.h"
#include "unity_minimal.h"

/** @brief Fill byte for the trailing garbage appended after a stream. */
typedef enum : uint8_t {
  k_tx_fill_trailing = 0xA5U, /**< Must be refused, not decoded. */
} tx_fill_t;

/**
 * @enum t_xz_t
 * @brief Allocation size, corruption mask and the relaxed ratio cap.
 */
typedef enum : uint32_t {
  k_t_alloc_exact  = 56U,      /**< Allocation that exactly exhausts the pool,
                                    so the next one must fail rather than wrap. */
  k_t_corrupt_mask = 0xFFU,    /**< XOR that flips a mid-stream byte to break
                                    the CRC64.                                  */
  k_t_ratio_loose  = 1000000U, /**< A compression-ratio cap high enough that the
                                    ratio guard cannot fire, isolating the other
                                    limits under test.                          */
} t_xz_t;

/**
 * @enum tx_dim_t
 * @brief Fixture geometry and buffer budgets (tests are magic-number exempt).
 */
typedef enum : uint32_t {
  k_tx_payload_4k  = 4096U,        /**< LCG payload length of the 4k fixture. */
  k_tx_small_rep   = 8U,           /**< Repetitions of the small text line.   */
  k_tx_scratch     = 192U * 1024U, /**< Session scratch (64k state + 128k dict
                                    *   budget -- holds the 64 KiB fixtures). */
  k_tx_arena       = 512U * 1024U, /**< Unwrap destination arena.             */
  k_tx_small_out   = 1024U,        /**< Deliberately undersized arena.        */
  k_tx_lcg_seed    = 0x12345678U,  /**< Payload LCG seed (matches generator). */
  k_tx_lcg_mul     = 1103515245U,  /**< Payload LCG multiplier.               */
  k_tx_lcg_add     = 12345U,       /**< Payload LCG increment.                */
  k_tx_lcg_shift   = 16U,          /**< Payload LCG output byte shift.        */
  k_tx_lcg_mask    = 0xFFU,        /**< Payload LCG output byte mask.         */
  k_tx_trailing    = 4U,           /**< Trailing garbage bytes appended.      */
  k_tx_truncate_by = 8U,           /**< Bytes cut off the truncated variant.  */
  k_tx_overreport  = 7U,           /**< Extra bytes a hostile reader reports. */
} tx_dim_t;

/** @brief Session scratch for every decode (8-aligned for the pool). */
alignas(8) static uint8_t s_scratch[k_tx_scratch];
/** @brief Unwrap destination arena. */
static uint8_t s_arena[k_tx_arena];
/** @brief Expected payload scratch (LCG or repeated text). */
static uint8_t s_expect[k_tx_payload_4k];

/** @brief Regenerate the 4 KiB LCG payload exactly as the fixture generator.
 *
 * @details Regenerates the fixture generator LCG byte stream for exact decoded-output comparison.
 * @param[out] dst Writable expected-payload buffer.
 * @param[in] n Number of bytes to regenerate.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_tx_lcg_fill(uint8_t* dst, size_t n)
{
  uint32_t s = (uint32_t)k_tx_lcg_seed;
  for (size_t i = 0U; i < n; ++i) {
    s      = ((uint32_t)k_tx_lcg_mul * s) + (uint32_t)k_tx_lcg_add;
    dst[i] = (uint8_t)((s >> (uint32_t)k_tx_lcg_shift) & (uint32_t)k_tx_lcg_mask);
  }
}

/** @brief Build the repeated-text payload; returns its length.
 *
 * @details Builds the repeated short-text payload used by both CRC32 and CRC64 fixture goldens.
 * @param[out] dst Writable repeated-text buffer.
 * @return Expected payload length.
 * @retval >0 The repeated fixture text was written.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static size_t internal_tx_small_fill(uint8_t* dst)
{
  static const char tx_small_line[] = "hello xz stream, bounded and fail-closed\n";
  const size_t      line            = sizeof(tx_small_line) - 1U; /* characters, without NUL */
  size_t            off             = 0U;
  for (uint32_t i = 0U; i < (uint32_t)k_tx_small_rep; ++i) {
    (void)memcpy(&dst[off], tx_small_line, line);
    off += line;
  }
  return off;
}

/** @brief Convenience: unwrap a flat buffer with optional custom limits.
 *
 * @details Invokes the production XZ wrapper with fixed caller-owned scratch and destination arenas.
 * @param[in] buf Complete XZ stream bytes.
 * @param[in] len Input length.
 * @param[in] lim Optional policy override.
 * @param[out] out_len Receives decoded bytes.
 * @return Decoder status.
 * @retval k_ra8_ok The stream decoded and validated.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static ra8_err_t
internal_tx_unwrap(const uint8_t* buf, size_t len, const ra8_decomp_limits_t* lim, size_t* out_len)
{
  unarch_mem_t mem = {.base = buf, .len = len};
  return unarch_xz_unwrap(unarch_mem_read,
                          &mem,
                          (uint64_t)len,
                          s_arena,
                          sizeof(s_arena),
                          s_scratch,
                          (uint32_t)sizeof(s_scratch),
                          lim,
                          out_len);
}

/**
 * @test internal_test_xz_pool_edges
 * @brief The bump arena rejects every invalid install / alloc and stays exact.
 *
 * @par MC/DC:
 * (no compound decisions under test -- every pool guard is an independent
 * single-condition early return.)

 *
 * @details Exercises arena installation, alignment, exact exhaustion, overflow rejection, and idempotent reset.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_pool_edges(void)
{
  TEST_BEGIN("xz pool: install/alloc/reset edges");
  unarch_xz_pool_reset();
  TEST_ASSERT_EQ(0U, unarch_xz_pool_used());
  TEST_ASSERT_NULL(unarch_xz_pool_alloc(16U)); /* no arena installed */

  TEST_ASSERT_EQ(k_ra8_err_null_ptr, unarch_xz_pool_install(nullptr, 64U));
  TEST_ASSERT_EQ(k_ra8_err_invalid_size, unarch_xz_pool_install(s_scratch, 0U));
  TEST_ASSERT_EQ(k_ra8_err_invalid_size, unarch_xz_pool_install(&s_scratch[1], 64U));

  TEST_ASSERT_EQ(k_ra8_ok, unarch_xz_pool_install(s_scratch, 64U));
  TEST_ASSERT_EQ(k_ra8_err_busy, unarch_xz_pool_install(s_scratch, 64U));

  TEST_ASSERT_NULL(unarch_xz_pool_alloc(0U)); /* zero request */
  void* a = unarch_xz_pool_alloc(3U);         /* rounds to 8  */
  TEST_ASSERT_NOT_NULL(a);
  TEST_ASSERT(a == &s_scratch[0]);
  TEST_ASSERT_EQ(8U, unarch_xz_pool_used());
  void* b = unarch_xz_pool_alloc(k_t_alloc_exact); /* exactly exhausts the arena */
  TEST_ASSERT_NOT_NULL(b);
  TEST_ASSERT_EQ(64U, unarch_xz_pool_used());
  TEST_ASSERT_NULL(unarch_xz_pool_alloc(1U));         /* exhausted           */
  TEST_ASSERT_NULL(unarch_xz_pool_alloc(UINT32_MAX)); /* rounding would wrap */
  unarch_xz_pool_reset();
  TEST_ASSERT_EQ(0U, unarch_xz_pool_used());
  unarch_xz_pool_reset(); /* idempotent */
  TEST_END("xz pool: install/alloc/reset edges");
}

/**
 * @test internal_test_xz_mem_read_edges
 * @brief The flat-memory read seam clamps every hostile offset / length.
 *
 * @par MC/DC:
 * (no compound decisions under test -- the view guards are independent
 * single-condition early returns.)

 *
 * @details Proves the flat-memory reader rejects null views and clamps offsets and lengths at the source boundary.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_mem_read_edges(void)
{
  TEST_BEGIN("xz io: flat-memory read seam clamps");
  uint8_t      src[4] = {1U, 2U, 3U, 4U};
  uint8_t      dst[8] = {};
  unarch_mem_t mem    = {.base = src, .len = sizeof(src)};

  TEST_ASSERT_EQ(0U, unarch_mem_read(nullptr, 0U, dst, 4U));
  unarch_mem_t dead = {};
  TEST_ASSERT_EQ(0U, unarch_mem_read(&dead, 0U, dst, 4U));
  TEST_ASSERT_EQ(0U, unarch_mem_read(&mem, 0U, nullptr, 4U));
  TEST_ASSERT_EQ(0U, unarch_mem_read(&mem, 4U, dst, 4U)); /* at EOF       */
  TEST_ASSERT_EQ(0U, unarch_mem_read(&mem, 0U, dst, 0U)); /* zero request */
  TEST_ASSERT_EQ(2U, unarch_mem_read(&mem, 2U, dst, 8U)); /* clamped tail */
  TEST_ASSERT_EQ(3U, dst[0]);
  TEST_ASSERT_EQ(4U, dst[1]);
  TEST_ASSERT_EQ(4U, unarch_mem_read(&mem, 0U, dst, 4U)); /* exact */
  TEST_END("xz io: flat-memory read seam clamps");
}

/**
 * @test internal_test_xz_magic_probe
 * @brief The signature probe accepts only the six XZ magic bytes.
 *
 * @par MC/DC:
 * (no compound decisions under test -- NULL and length guards are
 * independent single-condition early returns; the byte compare is memeq.)

 *
 * @details Checks exact XZ magic acceptance and each short or mismatched prefix rejection.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_magic_probe(void)
{
  TEST_BEGIN("xz: magic probe");
  TEST_ASSERT(!unarch_xz_magic(nullptr, 6U));
  TEST_ASSERT(!unarch_xz_magic(k_fx_xz_crc32, 5U)); /* too short */
  TEST_ASSERT(unarch_xz_magic(k_fx_xz_crc32, sizeof(k_fx_xz_crc32)));
  const uint8_t junk[6] = {0x50U, 0x4BU, 0x03U, 0x04U, 0x00U, 0x00U};
  TEST_ASSERT(!unarch_xz_magic(junk, sizeof(junk)));
  TEST_END("xz: magic probe");
}

/**
 * @test internal_test_xz_session_guards
 * @brief begin/run/end argument and liveness guards fail closed.
 *
 * @par MC/DC:
 * (no compound decisions under test -- each guard is an independent
 * single-condition early return.)

 *
 * @details Exercises session initialization, step, finish, and reset guards around caller-owned scratch.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_session_guards(void)
{
  TEST_BEGIN("xz: session guards");
  unarch_xz_stream_t xs = {};
  TEST_ASSERT_EQ(k_ra8_err_null_ptr, unarch_xz_stream_begin(nullptr, s_scratch, 1U));
  TEST_ASSERT_EQ(k_ra8_err_null_ptr, unarch_xz_stream_begin(&xs, nullptr, 1U));
  TEST_ASSERT_EQ(k_ra8_err_invalid_size,
                 unarch_xz_stream_begin(&xs, s_scratch, (uint32_t)k_unarch_xz_state_reserve));
  TEST_ASSERT_EQ(k_ra8_err_invalid_size,
                 unarch_xz_stream_begin(&xs, &s_scratch[1], (uint32_t)sizeof(s_scratch) - 1U));

  size_t  iu      = 0U;
  size_t  ou      = 0U;
  bool    end     = false;
  uint8_t outb[8] = {};
  TEST_ASSERT_EQ(k_ra8_err_null_ptr,
                 unarch_xz_stream_run(nullptr, nullptr, 0U, &iu, outb, 8U, &ou, &end));
  TEST_ASSERT_EQ(k_ra8_err_null_ptr,
                 unarch_xz_stream_run(&xs, nullptr, 0U, nullptr, outb, 8U, &ou, &end));
  TEST_ASSERT_EQ(k_ra8_err_null_ptr,
                 unarch_xz_stream_run(&xs, nullptr, 0U, &iu, nullptr, 8U, &ou, &end));
  TEST_ASSERT_EQ(k_ra8_err_null_ptr,
                 unarch_xz_stream_run(&xs, nullptr, 0U, &iu, outb, 8U, nullptr, &end));
  TEST_ASSERT_EQ(k_ra8_err_null_ptr,
                 unarch_xz_stream_run(&xs, nullptr, 0U, &iu, outb, 8U, &ou, nullptr));
  TEST_ASSERT_EQ(k_ra8_err_null_ptr,
                 unarch_xz_stream_run(&xs, nullptr, 4U, &iu, outb, 8U, &ou, &end));
  TEST_ASSERT_EQ(k_ra8_err_invalid_state,
                 unarch_xz_stream_run(&xs, outb, 0U, &iu, outb, 8U, &ou, &end));

  unarch_xz_stream_end(nullptr); /* NULL-safe        */
  unarch_xz_stream_end(&xs);     /* never-begun-safe */

  /* A live session refuses a second concurrent begin (single-client pool). */
  TEST_ASSERT_EQ(k_ra8_ok, unarch_xz_stream_begin(&xs, s_scratch, (uint32_t)sizeof(s_scratch)));
  TEST_ASSERT(unarch_xz_pool_used() > 0U); /* state + dict came from the scratch */
  unarch_xz_stream_t xs2 = {};
  TEST_ASSERT_EQ(k_ra8_err_busy,
                 unarch_xz_stream_begin(&xs2, s_scratch, (uint32_t)sizeof(s_scratch)));
  unarch_xz_stream_end(&xs);
  TEST_ASSERT_EQ(0U, unarch_xz_pool_used());
  TEST_END("xz: session guards");
}

/**
 * @test internal_test_xz_unwrap_guards
 * @brief unwrap argument validation fails closed before any decode.
 *
 * @par MC/DC:
 * (no compound decisions under test -- each guard is an independent
 * single-condition early return.)

 *
 * @details Checks every unwrap pointer, size, alignment, and limit guard before decoder state is published.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_unwrap_guards(void)
{
  TEST_BEGIN("xz: unwrap argument guards");
  size_t       got = 1U;
  unarch_mem_t mem = {.base = k_fx_xz_crc32, .len = sizeof(k_fx_xz_crc32)};
  TEST_ASSERT_EQ(k_ra8_err_null_ptr,
                 unarch_xz_unwrap(nullptr, &mem, 8U, s_arena, 8U, s_scratch, 8U, nullptr, &got));
  TEST_ASSERT_EQ(
    k_ra8_err_null_ptr,
    unarch_xz_unwrap(unarch_mem_read, &mem, 8U, nullptr, 8U, s_scratch, 8U, nullptr, &got));
  TEST_ASSERT_EQ(
    k_ra8_err_null_ptr,
    unarch_xz_unwrap(unarch_mem_read, &mem, 8U, s_arena, 8U, nullptr, 8U, nullptr, &got));
  TEST_ASSERT_EQ(
    k_ra8_err_null_ptr,
    unarch_xz_unwrap(unarch_mem_read, &mem, 8U, s_arena, 8U, s_scratch, 8U, nullptr, nullptr));

  TEST_ASSERT_EQ(k_ra8_err_invalid_size, internal_tx_unwrap(k_fx_xz_crc32, 0U, nullptr, &got));
  TEST_ASSERT_EQ(0U, got);
  TEST_ASSERT_EQ(k_ra8_err_invalid_size,
                 unarch_xz_unwrap(unarch_mem_read,
                                  &mem,
                                  (uint64_t)sizeof(k_fx_xz_crc32),
                                  s_arena,
                                  0U,
                                  s_scratch,
                                  (uint32_t)sizeof(s_scratch),
                                  nullptr,
                                  &got));

  ra8_decomp_limits_t bad = ra8_decomp_limits_default();
  bad.max_ratio           = 0U;
  TEST_ASSERT_EQ(k_ra8_err_invalid_arg,
                 internal_tx_unwrap(k_fx_xz_crc32, sizeof(k_fx_xz_crc32), &bad, &got));

  /* Undersized scratch propagates from the session begin. */
  TEST_ASSERT_EQ(k_ra8_err_invalid_size,
                 unarch_xz_unwrap(unarch_mem_read,
                                  &mem,
                                  (uint64_t)sizeof(k_fx_xz_crc32),
                                  s_arena,
                                  sizeof(s_arena),
                                  s_scratch,
                                  (uint32_t)k_unarch_xz_state_reserve,
                                  nullptr,
                                  &got));
  TEST_END("xz: unwrap argument guards");
}

/**
 * @test internal_test_xz_unwrap_honest_streams
 * @brief CRC64 (multi-pass) and CRC32 streams decode byte-exactly.
 *
 * @par MC/DC:
 * (no compound decisions under test -- the unwrap loop conditions are
 * independent single-condition guards, each driven by a hostile variant
 * elsewhere in this suite.)

 *
 * @details Decodes committed CRC32 and CRC64 fixtures and compares all bytes against regenerated payloads.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_unwrap_honest_streams(void)
{
  TEST_BEGIN("xz: honest CRC64 + CRC32 streams decode");
  size_t got = 0U;
  TEST_ASSERT_EQ(k_ra8_ok,
                 internal_tx_unwrap(k_fx_xz_crc64_4k, sizeof(k_fx_xz_crc64_4k), nullptr, &got));
  TEST_ASSERT_EQ(k_tx_payload_4k, got);
  internal_tx_lcg_fill(s_expect, (size_t)k_tx_payload_4k);
  TEST_ASSERT_EQ(0, memcmp(s_arena, s_expect, (size_t)k_tx_payload_4k));

  got = 0U;
  TEST_ASSERT_EQ(k_ra8_ok, internal_tx_unwrap(k_fx_xz_crc32, sizeof(k_fx_xz_crc32), nullptr, &got));
  const size_t small_len = internal_tx_small_fill(s_expect);
  TEST_ASSERT_EQ(small_len, got);
  TEST_ASSERT_EQ(0, memcmp(s_arena, s_expect, small_len));
  TEST_END("xz: honest CRC64 + CRC32 streams decode");
}

/** @brief Hostile read fn: honest bytes but an over-reported byte count.
 *
 * @details Wraps the memory reader but deliberately reports more bytes than requested to model a hostile source.
 * @param[in] ctx Memory-reader context.
 * @param[in] offset Requested source offset.
 * @param[out] buf Caller destination buffer.
 * @param[in] len Requested byte count.
 * @return Hostile reported read length.
 * @retval >0 Returns the underlying count plus the deliberate over-report delta.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static size_t internal_tx_read_overreport(void* ctx, uint64_t offset, void* buf, size_t len)
{
  const size_t n = unarch_mem_read(ctx, offset, buf, len);
  if (n == 0U) {
    return 0U;
  }
  return n + (size_t)k_tx_overreport; /* lies about how much it produced */
}

/**
 * @test internal_test_xz_unwrap_hostile_reader
 * @brief A backing that over-reports its read count is clamped, not trusted.
 *
 * @par MC/DC:
 * (no compound decisions under test -- the clamp is a single-condition
 * guard; this vector drives its true arm, every other test its false arm.)

 *
 * @details Proves a reader that over-reports progress is rejected without exceeding caller-owned buffers.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_unwrap_hostile_reader(void)
{
  TEST_BEGIN("xz: over-reporting reader is clamped");
  unarch_mem_t mem = {.base = k_fx_xz_crc32, .len = sizeof(k_fx_xz_crc32)};
  size_t       got = 0U;
  TEST_ASSERT_EQ(k_ra8_ok,
                 unarch_xz_unwrap(internal_tx_read_overreport,
                                  &mem,
                                  (uint64_t)sizeof(k_fx_xz_crc32),
                                  s_arena,
                                  sizeof(s_arena),
                                  s_scratch,
                                  (uint32_t)sizeof(s_scratch),
                                  nullptr,
                                  &got));
  const size_t small_len = internal_tx_small_fill(s_expect);
  TEST_ASSERT_EQ(small_len, got);
  TEST_ASSERT_EQ(0, memcmp(s_arena, s_expect, small_len));
  TEST_END("xz: over-reporting reader is clamped");
}

/**
 * @test internal_test_xz_unwrap_rejects_hostile_streams
 * @brief Every malformed / unsupported stream shape is rejected fail-closed.
 *
 * @par MC/DC:
 * (no compound decisions under test -- each rejection exercises one
 * single-condition mapping arm of `internal_xz_map_err` / the unwrap loop.)

 *
 * @details Covers unsupported checks, oversized dictionaries, corruption, truncation, trailing bytes, and non-XZ input.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_unwrap_rejects_hostile_streams(void)
{
  static uint8_t s_mut[sizeof(k_fx_xz_crc64_4k) + k_tx_trailing];
  TEST_BEGIN("xz: hostile stream shapes rejected");
  size_t got = 1U;

  /* SHA-256 integrity check: not compiled in, must reject (never mis-decode). */
  TEST_ASSERT_EQ(
    k_ra8_err_not_supported,
    internal_tx_unwrap(k_fx_xz_special.sha256, sizeof(k_fx_xz_special.sha256), nullptr, &got));
  TEST_ASSERT_EQ(0U, got);

  /* Declared 8 MiB dictionary exceeds the scratch budget: reject, no growth. */
  got = 1U;
  TEST_ASSERT_EQ(
    k_ra8_err_no_mem,
    internal_tx_unwrap(k_fx_xz_special.bigdict, sizeof(k_fx_xz_special.bigdict), nullptr, &got));
  TEST_ASSERT_EQ(0U, got);

  /* Not an XZ stream at all. */
  got              = 1U;
  uint8_t junk[32] = {};
  junk[0]          = 0x50U;
  junk[1]          = 0x4BU;
  junk[2]          = 0x03U;
  junk[3]          = 0x04U;
  TEST_ASSERT_EQ(k_ra8_err_not_supported, internal_tx_unwrap(junk, sizeof(junk), nullptr, &got));
  TEST_ASSERT_EQ(0U, got);

  /* One corrupted payload byte: integrity check must catch it. */
  got = 1U;
  (void)memcpy(s_mut, k_fx_xz_crc64_4k, sizeof(k_fx_xz_crc64_4k));
  s_mut[sizeof(k_fx_xz_crc64_4k) / 2U] ^= k_t_corrupt_mask;
  TEST_ASSERT_EQ(k_ra8_err_validation_failed,
                 internal_tx_unwrap(s_mut, sizeof(k_fx_xz_crc64_4k), nullptr, &got));
  TEST_ASSERT_EQ(0U, got);

  /* Truncated stream: the backing runs dry under the decoder. */
  got = 1U;
  TEST_ASSERT_EQ(k_ra8_err_validation_failed,
                 internal_tx_unwrap(k_fx_xz_crc64_4k,
                                    sizeof(k_fx_xz_crc64_4k) - (size_t)k_tx_truncate_by,
                                    nullptr,
                                    &got));
  TEST_ASSERT_EQ(0U, got);

  /* Trailing garbage after the verified footer: reject (no concatenation). */
  got = 1U;
  (void)memcpy(s_mut, k_fx_xz_crc64_4k, sizeof(k_fx_xz_crc64_4k));
  (void)memset(&s_mut[sizeof(k_fx_xz_crc64_4k)], k_tx_fill_trailing, (size_t)k_tx_trailing);
  TEST_ASSERT_EQ(
    k_ra8_err_validation_failed,
    internal_tx_unwrap(s_mut, sizeof(k_fx_xz_crc64_4k) + (size_t)k_tx_trailing, nullptr, &got));
  TEST_ASSERT_EQ(0U, got);
  TEST_END("xz: hostile stream shapes rejected");
}

/**
 * @brief Unwrap an xz stream into the shared small arena via the memory reader.
 * @param[in]  mem   Backing-memory descriptor over the xz stream.
 * @param[in]  inlen Consumable input length in bytes.
 * @param[in]  lim   Optional decompression limits (nullptr for defaults).
 * @param[out] got   Receives the number of output bytes produced.
 * @return The `unarch_xz_unwrap` result code.
 * @pre @p mem references a valid xz stream.
 * @post No state beyond the shared arena and @p got is modified.
 * @note Not thread-safe; single-threaded host-test helper.
 * @since 0.1.0

 *
 * @details Runs one memory-backed decode with a caller-selected output arena and policy object.
 * @retval k_ra8_ok The stream decoded within the supplied limits.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @post All writes remain within caller-owned fixture storage.
 */
RA8_INTERNAL
static ra8_err_t
internal_tx_unwrap_arena(unarch_mem_t* mem, size_t inlen, ra8_decomp_limits_t* lim, size_t* got)
{
  return unarch_xz_unwrap(unarch_mem_read,
                          mem,
                          (uint64_t)inlen,
                          s_arena,
                          (size_t)k_tx_small_out,
                          s_scratch,
                          (uint32_t)sizeof(s_scratch),
                          lim,
                          got);
}

/**
 * @test internal_test_xz_unwrap_policy_bounds
 * @brief Each decompression-limits axis fires: ratio (default policy),
 *        output cap, iteration budget, and the undersized-arena shapes.
 *
 * @par MC/DC:
 * (no compound decisions under test -- each breach exercises one
 * single-condition budget charge in `ra8_decomp_limits.c` or one arm of
 * the unwrap loop's arena-full mapping.)

 *
 * @details Drives output, iteration, and compression-ratio budgets at their acceptance and rejection boundaries.
 * @pre All input spans and fixture capacities satisfy the bounds stated by this helper.
 * @pre The caller has initialized any state that this helper consumes or advances.
 * @post All writes remain within caller-owned fixture storage.
 * @post No heap allocation or external I/O is performed.
 * @note Test-only and not reentrant because fixtures use file-scope scratch storage.
 * @since Version 0.1.0
 */
RA8_INTERNAL
static void internal_test_xz_unwrap_policy_bounds(void)
{
  TEST_BEGIN("xz: policy bounds fire");
  size_t got = 1U;

  /* A 1 MiB zeros bomb in a 284-byte stream breaches the DEFAULT ratio
   * bound (1024:1 + 64 KiB grace) about 356 KiB in -- far inside the
   * 512 KiB arena, proving the bomb dies by policy, not by buffer size. */
  TEST_ASSERT_EQ(
    k_ra8_err_decomp_ratio,
    internal_tx_unwrap(k_fx_xz_special.bomb_1m, sizeof(k_fx_xz_special.bomb_1m), nullptr, &got));
  TEST_ASSERT_EQ(0U, got);

  /* Tightened output cap fires before the honest stream completes. */
  got                     = 1U;
  ra8_decomp_limits_t lim = ra8_decomp_limits_default();
  lim.max_output_bytes    = (uint64_t)k_tx_small_out;
  TEST_ASSERT_EQ(k_ra8_err_decomp_output_cap,
                 internal_tx_unwrap(k_fx_xz_crc64_4k, sizeof(k_fx_xz_crc64_4k), &lim, &got));
  TEST_ASSERT_EQ(0U, got);

  /* Tightened iteration budget: the 4156-byte stream needs several 512-byte
   * refill passes, so a 1-iteration budget dies on pass two. */
  got                = 1U;
  lim                = ra8_decomp_limits_default();
  lim.max_iterations = 1U;
  TEST_ASSERT_EQ(k_ra8_err_decomp_iterations,
                 internal_tx_unwrap(k_fx_xz_crc64_4k, sizeof(k_fx_xz_crc64_4k), &lim, &got));
  TEST_ASSERT_EQ(0U, got);

  /* Arena smaller than the payload, input fully consumable: the stream can
   * never end, the backing runs dry, and the full arena maps to no_mem. */
  got              = 1U;
  unarch_mem_t mem = {.base = k_fx_xz_crc64_4k, .len = sizeof(k_fx_xz_crc64_4k)};
  TEST_ASSERT_EQ(k_ra8_err_no_mem,
                 internal_tx_unwrap_arena(&mem, sizeof(k_fx_xz_crc64_4k), nullptr, &got));
  TEST_ASSERT_EQ(0U, got);

  /* Arena smaller than the payload with input left over: the decoder stalls
   * (dict cannot flush), reports no progress, and the full arena maps to
   * no_mem through the stuck-stream arm. Ratio is loosened so the policy
   * does not fire first on this bomb-shaped stream. */
  got                       = 1U;
  ra8_decomp_limits_t loose = ra8_decomp_limits_default();
  loose.max_ratio           = k_t_ratio_loose;
  unarch_mem_t bomb = {.base = k_fx_xz_special.bomb_1m, .len = sizeof(k_fx_xz_special.bomb_1m)};
  TEST_ASSERT_EQ(k_ra8_err_no_mem,
                 internal_tx_unwrap_arena(&bomb, sizeof(k_fx_xz_special.bomb_1m), &loose, &got));
  TEST_ASSERT_EQ(0U, got);
  TEST_END("xz: policy bounds fire");
}

/**
 * @brief Test entry point -- runs the XZ wrapper suite in order.
 * @return 0 on success; unity_minimal.h exits non-zero on the first failure.
 */
int main(void)
{
  internal_test_xz_pool_edges();
  internal_test_xz_mem_read_edges();
  internal_test_xz_magic_probe();
  internal_test_xz_session_guards();
  internal_test_xz_unwrap_guards();
  internal_test_xz_unwrap_honest_streams();
  internal_test_xz_unwrap_hostile_reader();
  internal_test_xz_unwrap_rejects_hostile_streams();
  internal_test_xz_unwrap_policy_bounds();
  return 0;
}
