# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Brighton Sikarskie
---
- name: Restart apt-cacher-ng
  ansible.builtin.service:
    name: apt-cacher-ng
    state: restarted

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
