/**
 * @file ra8_media_download.pb-c.h
 * @brief Generated protobuf-C declarations for the media-download protocol.
 *
 * @details
 * Generated from `ra8_media_download.proto` by the pinned protobuf-C compiler.
 * Do not edit this file directly; use `scripts/gen/gen_ra8_media_proto.sh` so
 * the checked-in codec and its attribution remain reproducible.
 * C23HDR-OK: protoc-c 1.5.2 owns the classic guard and enum ABI.
 *
 * @copyright Copyright (c) 2026 Brighton Sikarskie
 * SPDX-License-Identifier: MIT
 */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ra8_media_download.proto */

#ifndef PROTOBUF_C_ra8_5fmedia_5fdownload_2eproto__INCLUDED
#define PROTOBUF_C_ra8_5fmedia_5fdownload_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Ra8__Mdl__StartRequest Ra8__Mdl__StartRequest;
typedef struct Ra8__Mdl__Accepted Ra8__Mdl__Accepted;
typedef struct Ra8__Mdl__NextRequest Ra8__Mdl__NextRequest;
typedef struct Ra8__Mdl__Chunk Ra8__Mdl__Chunk;
typedef struct Ra8__Mdl__CancelRequest Ra8__Mdl__CancelRequest;
typedef struct Ra8__Mdl__Cancelled Ra8__Mdl__Cancelled;


/* --- enums --- */

/*
 * Values intentionally match ra8_mdl_format_t. Keep the generated and shared
 * enums synchronized; production TUs assert the mapping at compile time.
 */
typedef enum _Ra8__Mdl__Format { /* C23HDR-OK: protoc-c 1.5.2 owns this enum ABI. */
  RA8__MDL__FORMAT__FORMAT_LOOSE = 0,
  RA8__MDL__FORMAT__FORMAT_CBZ = 1,
  RA8__MDL__FORMAT__FORMAT_CBT = 2,
  RA8__MDL__FORMAT__FORMAT_CBR = 3,
  RA8__MDL__FORMAT__FORMAT_CBT_XZ = 4,
  RA8__MDL__FORMAT__FORMAT_CBT_GZ = 5,
  RA8__MDL__FORMAT__FORMAT_EPUB = 6,
  RA8__MDL__FORMAT__FORMAT_JOF = 7,
  RA8__MDL__FORMAT__FORMAT_RABOOK = 8,
  RA8__MDL__FORMAT__FORMAT_INVALID = 255
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RA8__MDL__FORMAT)
} Ra8__Mdl__Format;
typedef enum _Ra8__Mdl__State { /* C23HDR-OK: protoc-c 1.5.2 owns this enum ABI. */
  RA8__MDL__STATE__STATE_UNSPECIFIED = 0,
  RA8__MDL__STATE__STATE_ACCEPTED = 1,
  RA8__MDL__STATE__STATE_DOWNLOADING = 2,
  RA8__MDL__STATE__STATE_COMPLETE = 3,
  RA8__MDL__STATE__STATE_CANCELLED = 4,
  RA8__MDL__STATE__STATE_FAILED = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RA8__MDL__STATE)
} Ra8__Mdl__State;

/* --- messages --- */

struct  Ra8__Mdl__StartRequest
{
  ProtobufCMessage base;
  uint32_t protocol_version;
  char *url;
  Ra8__Mdl__Format format;
  char *user_agent;
  char *referer;
  char *if_none_match;
  char *if_modified_since;
  uint32_t timeout_ms;
};
#define RA8__MDL__START_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ra8__mdl__start_request__descriptor) \
, 0, (char *)protobuf_c_empty_string, RA8__MDL__FORMAT__FORMAT_LOOSE, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Ra8__Mdl__Accepted
{
  ProtobufCMessage base;
  uint32_t protocol_version;
  uint32_t job_id;
  uint32_t max_chunk_bytes;
  Ra8__Mdl__Format format;
};
#define RA8__MDL__ACCEPTED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ra8__mdl__accepted__descriptor) \
, 0, 0, 0, RA8__MDL__FORMAT__FORMAT_LOOSE }


struct  Ra8__Mdl__NextRequest
{
  ProtobufCMessage base;
  uint32_t protocol_version;
  uint32_t job_id;
  uint64_t acknowledged_offset;
  uint32_t max_bytes;
};
#define RA8__MDL__NEXT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ra8__mdl__next_request__descriptor) \
, 0, 0, 0, 0 }


struct  Ra8__Mdl__Chunk
{
  ProtobufCMessage base;
  uint32_t protocol_version;
  uint32_t job_id;
  uint32_t sequence;
  uint64_t offset;
  ProtobufCBinaryData data;
  uint64_t total_bytes;
  Ra8__Mdl__State state;
  int32_t status;
  ProtobufCBinaryData sha256;
  int32_t http_status;
  char *retry_after;
  char *etag;
  char *last_modified;
  char *content_type;
};
#define RA8__MDL__CHUNK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ra8__mdl__chunk__descriptor) \
, 0, 0, 0, 0, {0,NULL}, 0, RA8__MDL__STATE__STATE_UNSPECIFIED, 0, {0,NULL}, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Ra8__Mdl__CancelRequest
{
  ProtobufCMessage base;
  uint32_t protocol_version;
  uint32_t job_id;
};
#define RA8__MDL__CANCEL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ra8__mdl__cancel_request__descriptor) \
, 0, 0 }


struct  Ra8__Mdl__Cancelled
{
  ProtobufCMessage base;
  uint32_t protocol_version;
  uint32_t job_id;
  int32_t status;
};
#define RA8__MDL__CANCELLED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ra8__mdl__cancelled__descriptor) \
, 0, 0, 0 }


/* Ra8__Mdl__StartRequest methods */
void   ra8__mdl__start_request__init
                     (Ra8__Mdl__StartRequest         *message);
size_t ra8__mdl__start_request__get_packed_size
                     (const Ra8__Mdl__StartRequest   *message);
size_t ra8__mdl__start_request__pack
                     (const Ra8__Mdl__StartRequest   *message,
                      uint8_t             *out);
size_t ra8__mdl__start_request__pack_to_buffer
                     (const Ra8__Mdl__StartRequest   *message,
                      ProtobufCBuffer     *buffer);
Ra8__Mdl__StartRequest *
       ra8__mdl__start_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ra8__mdl__start_request__free_unpacked
                     (Ra8__Mdl__StartRequest *message,
                      ProtobufCAllocator *allocator);
/* Ra8__Mdl__Accepted methods */
void   ra8__mdl__accepted__init
                     (Ra8__Mdl__Accepted         *message);
size_t ra8__mdl__accepted__get_packed_size
                     (const Ra8__Mdl__Accepted   *message);
size_t ra8__mdl__accepted__pack
                     (const Ra8__Mdl__Accepted   *message,
                      uint8_t             *out);
size_t ra8__mdl__accepted__pack_to_buffer
                     (const Ra8__Mdl__Accepted   *message,
                      ProtobufCBuffer     *buffer);
Ra8__Mdl__Accepted *
       ra8__mdl__accepted__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ra8__mdl__accepted__free_unpacked
                     (Ra8__Mdl__Accepted *message,
                      ProtobufCAllocator *allocator);
/* Ra8__Mdl__NextRequest methods */
void   ra8__mdl__next_request__init
                     (Ra8__Mdl__NextRequest         *message);
size_t ra8__mdl__next_request__get_packed_size
                     (const Ra8__Mdl__NextRequest   *message);
size_t ra8__mdl__next_request__pack
                     (const Ra8__Mdl__NextRequest   *message,
                      uint8_t             *out);
size_t ra8__mdl__next_request__pack_to_buffer
                     (const Ra8__Mdl__NextRequest   *message,
                      ProtobufCBuffer     *buffer);
Ra8__Mdl__NextRequest *
       ra8__mdl__next_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ra8__mdl__next_request__free_unpacked
                     (Ra8__Mdl__NextRequest *message,
                      ProtobufCAllocator *allocator);
/* Ra8__Mdl__Chunk methods */
void   ra8__mdl__chunk__init
                     (Ra8__Mdl__Chunk         *message);
size_t ra8__mdl__chunk__get_packed_size
                     (const Ra8__Mdl__Chunk   *message);
size_t ra8__mdl__chunk__pack
                     (const Ra8__Mdl__Chunk   *message,
                      uint8_t             *out);
size_t ra8__mdl__chunk__pack_to_buffer
                     (const Ra8__Mdl__Chunk   *message,
                      ProtobufCBuffer     *buffer);
Ra8__Mdl__Chunk *
       ra8__mdl__chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ra8__mdl__chunk__free_unpacked
                     (Ra8__Mdl__Chunk *message,
                      ProtobufCAllocator *allocator);
/* Ra8__Mdl__CancelRequest methods */
void   ra8__mdl__cancel_request__init
                     (Ra8__Mdl__CancelRequest         *message);
size_t ra8__mdl__cancel_request__get_packed_size
                     (const Ra8__Mdl__CancelRequest   *message);
size_t ra8__mdl__cancel_request__pack
                     (const Ra8__Mdl__CancelRequest   *message,
                      uint8_t             *out);
size_t ra8__mdl__cancel_request__pack_to_buffer
                     (const Ra8__Mdl__CancelRequest   *message,
                      ProtobufCBuffer     *buffer);
Ra8__Mdl__CancelRequest *
       ra8__mdl__cancel_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ra8__mdl__cancel_request__free_unpacked
                     (Ra8__Mdl__CancelRequest *message,
                      ProtobufCAllocator *allocator);
/* Ra8__Mdl__Cancelled methods */
void   ra8__mdl__cancelled__init
                     (Ra8__Mdl__Cancelled         *message);
size_t ra8__mdl__cancelled__get_packed_size
                     (const Ra8__Mdl__Cancelled   *message);
size_t ra8__mdl__cancelled__pack
                     (const Ra8__Mdl__Cancelled   *message,
                      uint8_t             *out);
size_t ra8__mdl__cancelled__pack_to_buffer
                     (const Ra8__Mdl__Cancelled   *message,
                      ProtobufCBuffer     *buffer);
Ra8__Mdl__Cancelled *
       ra8__mdl__cancelled__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ra8__mdl__cancelled__free_unpacked
                     (Ra8__Mdl__Cancelled *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Ra8__Mdl__StartRequest_Closure)
                 (const Ra8__Mdl__StartRequest *message,
                  void *closure_data);
typedef void (*Ra8__Mdl__Accepted_Closure)
                 (const Ra8__Mdl__Accepted *message,
                  void *closure_data);
typedef void (*Ra8__Mdl__NextRequest_Closure)
                 (const Ra8__Mdl__NextRequest *message,
                  void *closure_data);
typedef void (*Ra8__Mdl__Chunk_Closure)
                 (const Ra8__Mdl__Chunk *message,
                  void *closure_data);
typedef void (*Ra8__Mdl__CancelRequest_Closure)
                 (const Ra8__Mdl__CancelRequest *message,
                  void *closure_data);
typedef void (*Ra8__Mdl__Cancelled_Closure)
                 (const Ra8__Mdl__Cancelled *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ra8__mdl__format__descriptor;
extern const ProtobufCEnumDescriptor    ra8__mdl__state__descriptor;
extern const ProtobufCMessageDescriptor ra8__mdl__start_request__descriptor;
extern const ProtobufCMessageDescriptor ra8__mdl__accepted__descriptor;
extern const ProtobufCMessageDescriptor ra8__mdl__next_request__descriptor;
extern const ProtobufCMessageDescriptor ra8__mdl__chunk__descriptor;
extern const ProtobufCMessageDescriptor ra8__mdl__cancel_request__descriptor;
extern const ProtobufCMessageDescriptor ra8__mdl__cancelled__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ra8_5fmedia_5fdownload_2eproto__INCLUDED */
