#pagebreak()
= Executable implementation contract

This section fixes first-pass software defaults. It does not authorize a live Proxmox change, a GitHub App installation, a branch-protection edit, a board operation, or a script deletion without its behavior proof. The implementation branch is `ci/ra8ci-implementation`, cut from `origin/ci/orchestrator` at `7ff60fee72cbc0d8e2754de9cff247fa5c24ee46`. The separate planner still owns issue and MR boundaries; this document defines engineering acceptance, not a stack.

== Repository layout and task migration

The Go module is `tools/ra8ci/go.mod` (`module github.com/bsikar/ra8-firmware/tools/ra8ci`), compiled as the `ra8ci` command for Linux amd64, Linux arm64 (the Raspberry Pi 5 board agent), and Windows amd64. Source packages are `internal/catalog`, `internal/cli`, `internal/server`, `internal/agent`, `internal/store`, `internal/github`, `internal/provision`, `internal/board`, and `internal/evidence`; their imports follow the boundaries in the preceding appendix. The command has `server`, `agent`, and task/board/report modes. Go 1.27.1 is already pinned by the devcontainer; the GitHub scale-set dependency is pinned to v0.4.0, not `latest`.

The reviewed catalog source is `tools/ra8ci/catalog/tasks.json`, schema version 1. It is embedded in the binary; `tools/ra8ci/catalog/sha256.txt` records the SHA-256 of canonical JSON (sorted keys, UTF-8, no insignificant whitespace). Each task record has `name`, `version`, `tier`, `scope`, `os`, `capabilities`, `args_schema`, `deadline_seconds`, `board_policy`, `steps`, `outputs`, `retry`, and `resource_hints`. Unknown fields, unknown task names, invalid arguments, digest mismatch, and unsupported schema fail closed. There are no compatibility adapters in v1. Pinned binary/package checks belong to deployment and CI; the app does not invent a second release-signing system.

The Phase 0 inventory and work-unit JSON are the exhaustive migration input. The migration ledger `tools/ra8ci/catalog/migration.json` has one row per in-scope used file: `old_path`, `callers`, `new_task_or_package`, `old_behavior_proof`, `new_behavior_proof`, `deletion_commit`, and `state`. A file with no standalone entry point maps to a Go package, not a fictitious CLI task. A migration first records golden success, failure, timeout, output/artifact, and selftest behavior from the old implementation; then runs the Go replacement against the same fixtures; then repoints every caller and deletes the old file in one change. Shelling out to that old file is an executor-stage adapter, not a completed port. No skipped or warning-bearing gate counts as proof. The planner's existing work units decide the eventual MR boundaries.

The first executable slice is local executor and evidence for four tasks, without board, Proxmox, or GitHub deployment. All four have catalog schema 1, no retry, one named command step, no board policy, and no output artifact beyond logs/receipt: `format` runs `bash scripts/checks/format_tree.sh`, is safe-local/write-working-tree, and has a 900-second deadline; `format-check` runs that script with `--check`, is safe-local/read-only, and has a 900-second deadline; `lint-go` runs `just quality::local::gate lint-go`, is safe-local/read-only with a 1200-second deadline; `test-go` runs `just quality::local::gate test-go`, is safe-local/read-only on Linux with a 1800-second deadline. Arguments are empty for all four. Each uses the verified repository root as working directory, inherits a scrubbed allowlist of environment variables, records exact exit and step duration, and fails if its tool is missing. No in-tree build output is allowed. Acceptance is equivalence of pass/fail and formatter diff on representative clean/failing fixtures plus 85-percent Go coverage/race gates.

The full product is not accepted at that slice: board control, GitHub capacity, provisioning, reports, and every inventory `used` helper remain required work. Subsequent slices follow the engineering dependencies in the architecture and the planner's work units. `build`, `emulator`, and `hil` become semantic entry points only when their Zig/out-of-tree build, emulator parity, and board safety contracts are available; a task name never silently becomes a no-op. The catalog may temporarily invoke the exact existing `just` recipe or `scripts/ci.sh --gate` under a controlled working directory while measurements accumulate. The current `RA8_GATE_REGISTRY` and CI-parity gate remain authoritative until each gate is absorbed. Zig steps are introduced only as #857's build-graph acceptance makes them available; ra8ci pins the Zig version, target, step, out-of-tree cache and artifact digest in each task catalog revision. It does not implement a parallel build graph. A generated per-task mapping is reviewed against the current `justfile`, imported `just/*.just`, hooks, and workflows before any call site moves.

== Internal result and CLI contract

Internal packages return a typed `Error` with code, operation ID, retryability, and cause. Codes are `invalid_argument`, `denied`, `conflict`, `stale_generation`, `expired`, `unavailable`, `deadline`, `cancelled`, `incomplete_evidence`, `unknown_external_outcome`, and `protocol_mismatch`; callers never infer retryability from message strings. `provision` returns unknown outcome after lost acknowledgment and demands reconciliation before retry. `store` reports failed commit as unavailable. `board` reports stale generation or recovery required. The server maps these to `application/problem+json`, and the CLI prints a short message or versioned JSON.

CLI exit categories are 0 success, 1 task failure, 2 usage/invalid argument, 3 unavailable, 4 denied, 5 deadline, 6 cancelled, 7 incomplete evidence, and 8 protocol mismatch. The exact child process exit code lives in the task attempt and `--json`; numeric child status is not overloaded as an orchestrator transport error. `ra8ci task --local` is allowed only for catalog tasks marked safe-local; `--dispatch` requires healthy server, audit, and database. `ra8ci run status|logs|cancel|retry|explain`, `board take|release|extend|status|queue|doctor|recover|quarantine`, and `report slow|critical-path|resource-fit|board|runners` are versioned command families. Human and JSON output expose the same result kind and evidence completeness.

== Identity, network, and credentials

The server ignores any actor or priority supplied in a request body. Human v1 identity is an operator-issued short-lived mTLS client certificate mapped to observer, submitter, board-human, or operator role in PostgreSQL; the client stores its key in protected user storage. Role grants are scoped by repository ID and optional board ID. An observer reads nonsecret run/report/board status only for granted repositories/boards. A submitter creates runs and may cancel/retry only its own runs within a granted repository; it cannot use human board priority. Board-human can request, extend, and use a named board but cannot cancel another holder or invoke recovery. Operator can inspect audit, quarantine/recover, drain, and cancel any scoped run with a reason; operator actions never bypass hardware neutrality. GitHub App, guest, and board-agent service principals have separate minimal scopes and cannot impersonate a human. Every read and mutation checks scope before data access and audits denial. The persistent board-side agent uses a distinct host certificate, an operator-approved enrollment and renewal path, and revocation checked on reconnect. A disposable guest receives a one-use enrollment token bound to a capacity reservation, exact VM marker, host class, and short expiry. Before GitHub job correlation it can report only health; after correlation, the server issues a separate task-scoped grant. Neither guest nor board agent receives database, GitHub App, or Proxmox credentials. Certificate issuer, approved principals, and rotation procedure must be named before production.

The control VM has an approved management address and no direct listener on the isolated guest bridge. A narrow L4 relay on a lab gateway may forward guest agent TLS to the control VM without terminating mTLS; an outbound proxy permits the official runner to reach GitHub's required domains and reviewed dependency endpoints. Guest firewall denies the management subnet, Proxmox API, PostgreSQL, and other guests. Provisioner-only SSH/WinRM is allowed through a constrained gateway. The specific bridge, relay IP, route, DNS/NTP service, and workflow egress list are operator-approved inputs, not inferred from reachable personal networking. An isolated Linux and Windows acceptance test must prove both permitted execution and forbidden management access.

The protected control VM and colocated PostgreSQL use separate unprivileged Unix identities and a database Unix socket. The runtime database role has no DDL and no UPDATE/DELETE on `audit`; a migration role alone changes schema. A dedicated scoped Proxmox API credential and a repository-scoped GitHub App key live only on this VM. No repo-controlled code or official runner executes there or on the Proxmox host. Until credential delivery and off-VM backup are approved, server/provisioner integration is tested with fakes and disposable local databases only.

== API and offline evidence

The `/v1` API requires TLS and an authenticated principal. Every mutation has `Idempotency-Key` (UUID) scoped to principal, method, path, and canonical body SHA-256. Exact replay returns the prior response; same key with different body returns 409. Errors use `application/problem+json` with `code`, `message`, `request_id`, `retryable`, and nonsecret `details`. Map invalid argument to 400, unauthenticated to 401, forbidden to 403, missing to 404, conflict/stale generation to 409, expired to 410, rate limit to 429, protocol mismatch to 426, and unavailable to 503. No endpoint accepts arbitrary shell text or an unreviewed path as a privileged argument.

`POST /v1/runs` accepts trigger, immutable source `{repo, commit, snapshot_sha256}`, catalog digest, task records `{key,name,args,depends_on_keys}`, and optional parent run ID. Keys are unique within a run; dependencies must name present keys and form an acyclic graph. The catalog separately declares dependencies among steps. It returns run ID and queued state. A failed, cancelled, timed-out, or evidence-incomplete prerequisite marks descendants skipped with a reason and makes the run non-success; skipped work is not counted as a pass. `task_edges` is populated from these validated task and step declarations. GitHub workflow-level edges are included only if an exact static `needs` graph from the pinned workflow commit can be mapped to observed jobs; otherwise `critical-path` labels the GitHub segment partial and reports no invented full-run path. `GET /v1/runs/{id}` includes execution result, cleanup status, evidence completeness, phase intervals, and task/attempt IDs. `POST /v1/runs/{id}/cancel` records intent and returns 202, not a claim of process termination. `GET /v1/runs/{id}/events?after=N` streams SSE with monotonically increasing per-run sequence, 15-second keepalive, `Last-Event-ID` resume, and an explicit retention-gap error. Reads are authorized by repository/run role and paginated with opaque cursors.

For direct `--dispatch`, the client snapshots its checkout into a deterministic archive containing tracked files and recursively pinned submodule content, rejects untracked/dirty content in v1, and hashes the complete archive. `POST /v1/source-staging` under the submitter identity reserves a one-use upload ID and bounded size/TTL; `PUT /v1/source-staging/{id}` streams the archive and verifies digest, length, path safety, and source metadata before atomic promotion. `POST /v1/runs` binds exactly one staged upload ID to the same principal, repository, commit, and digest in its admission transaction; an expired, reused, or mismatched upload fails. The target agent downloads and verifies size/digest, rejects absolute paths, `..`, and escaping symlinks, extracts into a per-attempt root, and verifies the embedded source commit and catalog before executing. GitHub jobs instead use the official runner's checkout; they do not accept a client-provided source tar as identity proof. Missing source evidence blocks dispatch, not a fallback clone of a mutable branch.

`POST /v1/agents/enroll` exchanges a one-use reservation-bound token, VM marker, version range, and host facts for a scoped identity. `GET /v1/agents/me/assignments?wait=25s` long-polls. `POST /v1/assignments/{id}/ack` echoes attempt ID and assignment version. A 5-second heartbeat reports current attempt, phase, host facts, and clock offset and returns cancel/yield intent. Assignment acknowledgment and terminal receipt are idempotent on stable attempt ID. A server absolute deadline is sent as remaining time; the agent enforces a monotonic local limit. Linux and Windows process-tree termination use bounded graceful then hard-stop phases, except board operations, which obey their declared indivisible segment and recovery contracts.

`POST /v1/attempts/{id}/chunks` accepts stream, sequence, step ID, monotonic offset, at most 64 KiB of bytes, and SHA-256. Duplicate sequence and digest succeeds; duplicate sequence with different digest conflicts. Backpressure causes a bounded encrypted agent spool, never silent log loss. Reconnect resumes from the last contiguous acknowledgment. `POST /v1/attempts/{id}/result` carries exact child exit, typed result, final sequence per stream, step summaries, and artifact digests. The attempt is not evidence-complete until all chunks and referenced artifacts are durable. `PUT /v1/artifacts/{sha256}` is attempt-scoped, length/digest checked, streamed to a temporary file, flushed, and atomically promoted. `GET /v1/artifacts/{sha256}` requires a task or board-agent grant. Board commands use lease ID and generation; reports include cohort, sample count, exclusions, and timing provenance.

`POST /v1/local-receipts` accepts the canonical receipt plus digest under a submitter identity and returns upload ID and `local_unverified` state; the server never turns it into a CI attestation. `GET /v1/runs/{id}/logs?after=N`, `GET /v1/reports/{slow|critical-path|resource-fit|board|runners|idle-time|regress}`, and board request/status/release/extend/yield/doctor/recover endpoints use the same versioned error envelope, role checks, opaque pagination and idempotency rule. Every board mutation includes board ID, lease ID, generation, reason, and a monotonic request ID; release and extension require the current holder, recovery requires operator role, and report filters are parsed typed values, not SQL fragments. The first report slice is `slow`, `board`, and `runners`; `idle-time`, `regress`, and full critical-path attribution follow only when the required samples and edges exist. No advertised report prints invented values when evidence is insufficient.

Safe local work writes a versioned canonical JSON receipt under `$XDG_STATE_HOME/ra8ci/spool` on Linux or `%LOCALAPPDATA%/ra8ci/spool` on Windows with a restrictive owner ACL. It includes receipt UUID, source/catalog/binary digests, task and argument digest, local-unverified actor/host, UTC endpoints, monotonic elapsed, exact child exit, step summaries, and log/artifact digests. Temp-write, file flush, atomic rename, and directory flush where supported make it durable. Corrupt/full spool is an explicit incomplete-evidence result. Upload by UUID and digest is idempotent; collision quarantines the receipt. A synced offline receipt remains `local_unverified`, never a CI gate attestation.

== Durable state and measurements

Use UUIDv7 for server run, task, attempt, reservation, and external-operation IDs; use UTC `timestamptz` for cross-host events and `bigint` monotonic offsets for local durations. Store run, task, attempt, step, dependency edge, resource sample, artifact, log chunk, board waiter/lease/session, board row, agent, GitHub job, runner lifecycle, external operation, idempotency key, run event, and audit tables. Primary identity/state is typed; JSONB is only versioned optional metadata. Unique keys include `(task_id, attempt_no)`, `(attempt_id, stream, seq)`, `(run_id, event_seq)`, guest marker, operation ID, and principal/method/path/idempotency key. Queue, sample, lease, and runner-state indexes follow their query keys. The board has generation and recovery-required columns plus a partial unique index for one pending/active lease per board. Every state transition uses version compare-and-swap and writes its audit/event row in the same transaction. Forward-only migrations run with a separate role; startup refuses an incompatible schema or unsafe downgrade.

Run phases are accepted, queued, provisioning, ready, running, draining, cleaning, then terminal. Execution result is separate from cleanup result so a successful command followed by an orphan guest is `cleanup_failed` overall. Task state is scheduled, assigned, running, terminal. Attempt state is issued, acknowledged, running, then succeeded, failed, timed_out, cancelled, preempted, or lost. A retry gets a new attempt ID and never overwrites the old one. Runner lifecycle is requested, provisioning, healthy, JIT issued, registered idle, busy, draining, deregistered, destroyed, with reconcile-required side state. Commit external intent, exact expected identity, and operation ID before side effect; after lost acknowledgment inspect state, Proxmox marker, GitHub runner, and agent facts before retrying.

Native ra8ci queue admission caps outstanding requests at 100 per profile, returning retryable 429 above the cap. Required tasks outrank optional, which outrank nightly; FIFO orders each tier. Every full minute waiting moves an optional/nightly task up one effective tier, capped at required, but it does not interrupt a running task. Host caps come from the reviewed fleet declaration and free-RAM/disk checks; no overcommit is inferred from low instantaneous load. If a profile has at least two slots, one is reserved for queued required tasks with predicted duration at most 10 minutes; the slot may be borrowed when no such task waits and is returned only at a task boundary. Quiet-hours denial is an admission condition, not a guessed host fact. GitHub owns its workflow queue; the separate ra8ci capacity controller never attempts to reorder its jobs.

Process-tree samples occur every 5 seconds and at step boundaries. Record actual interval, dropped count, CPU time/utilization, process-tree RSS/peak, load, free RAM, disk and network I/O, agent monotonic offset, server receive time, and clock-skew estimate. Cross-host durations never subtract unsynchronized clocks. Raw logs, firmware, and other artifacts use SHA-256 content-addressed files on an encrypted persistent control-VM volume; PostgreSQL stores metadata/pointers. Redact secrets before persistence. Draft retention is 30 days raw logs, 90 days samples/artifacts, one year run metadata, two years audit, and board baseline images while referenced; incident evidence is pinned. Reports show `insufficient data` for p90 when fewer than 20 comparable attempts exist and include failures/exclusions, host, engine, profile, cache state, catalog version, and timing uncertainty. Tier changes remain human-reviewed.

== GitHub scale-set and required result

Use `github.com/actions/scaleset` v0.4.0 at tag commit `6ce025902cd964747a078c2aabe7340ebc667eca`. The first isolated prototype uses repository scope `https://github.com/bsikar/ra8-firmware`, single-label sets `ra8ci-linux-amd64` and `ra8ci-windows-amd64`, minimum idle 0 and maximum one guest each. Production labels, runner group, quotas, image digest, and runner release require review. The App needs repository Administration write, Actions read, Checks write, and Metadata read; installation is not implied. `TotalAssignedJobs` drives desired capacity, and honest maximum-capacity reporting is bounded by approved Proxmox budgets. Provisioning, idle, and busy guests count against capacity; busy workers are never destroyed for scale-down.

The v0.4.0 listener acknowledges messages before invoking scaler callbacks. Wrap its message client so normalized message ID, session, statistics, and required job fields commit to a durable inbox before acknowledgment; callbacks commit idempotent outbox intent, not external side effects. Replay inbox/outbox after restart and reconcile GitHub runner list, Terraform state, Proxmox marker, and agent receipts. Unknown message types or canceled/requeued assignments trigger REST backfill, not assumed success. A capacity reservation binds guest VM ID/marker and Terraform state path before guest enrollment. An idle guest grant permits only health. Bind runner ID/name and reservation to trusted GitHub job events, then use the paginated workflow-jobs REST API to verify repository, workflow run, attempt, job ID, runner request/runner identity, and head SHA before issuing any task grant. Missing or contradictory correlation remains unverified and blocks positive results.

The official runner owns the GitHub job conclusion. Before issuing JIT, the controller uses Actions-read REST polling of queued *jobs* in queued or in-progress workflow run attempts, including a downstream `needs` job in an already-running workflow, to discover repository, run ID, attempt, head SHA, job ID, and target scale-set label. It holds a capacity reservation without JIT if this lookup has not converged; it does not need a public inbound webhook. A single App check named `ra8ci / <workflow> / lifecycle`, keyed by workflow run/attempt in `external_id`, is created in progress on that head SHA before a matching guest can take work. All jobs in that workflow attempt that target ra8ci sets are recorded from the job listing, including not-yet-ready `needs` descendants; the check remains pending until the workflow attempt is terminal and every such job's assigned runner, agent evidence, and guest cleanup has a verified terminal outcome. A newly discovered matrix job extends the set while pending. Missing job correlation or cleanup makes the aggregate fail, never silently pass. On same-SHA concurrent runs, each check has a distinct external ID; the prototype must prove the repository's required-check semantics before this check becomes an authoritative branch gate.

Failure, cancellation, timeout, missing evidence, and cleanup failure make the separate lifecycle check fail; the native job check cannot be retroactively changed. The protected branch requires the lifecycle check from the ra8ci App in addition to native checks only after acceptance. An uncertain Checks API write is reconciled by listing check runs for SHA/name/App/external ID, not blindly repeated. If queued-job discovery or pending-check publication fails, advertise zero new capacity. Reruns and concurrent runs on one SHA are explicit acceptance cases. No protected-branch rule is changed without owner approval.

Inside the one-job guest, the official runner's `just` recipe calls the local `ra8ci` CLI through a Unix socket or Windows named pipe served by the agent. OS peer identity must be the runner service account; a caller-supplied GitHub environment variable is only a hint. If the server's verified job grant has not arrived, the CLI waits at most 60 seconds while the agent refreshes correlation, then fails closed; cancellation interrupts the wait. The server's reviewed policy catalog maps `(repository ID, trusted workflow path/ref, job name, event class, runner scale set)` to an explicit set of allowed task names and argument schema versions. It is embedded in the server binary, never taken from PR-controlled workflow YAML; fork PRs and untrusted refs cannot receive board or provisioner capabilities. A HIL task additionally requires the dedicated HIL workflow/job identity and board lease, not merely an agent label. The agent accepts only those catalog tasks under a verified job grant, executes as a nonprivileged task identity, and associates logs/results with the server-issued attempt. It verifies the canonical `GITHUB_WORKSPACE` path lies under the runner's dedicated work root and its checked-out commit matches the verified GitHub head SHA; it rejects symlink escape and mismatches. Job completion revokes the grant. A background workflow process cannot gain a new grant after the one job ends. A compromised guest can still falsify its own workspace or availability, so its reports are labeled guest-origin evidence, not a cryptographic proof of firmware correctness; the disposable boundary protects management credentials and later jobs.

== Board, artifact, and physical recovery

The persistent Pi board agent is the sole software executor for J-Link, UART, reset, relay, and power actions. Restrict SSH and device ACLs so disposable guests and legacy scripts cannot touch these devices directly after cutover. It owns child process groups and a local serialized gate, persists its highest installed generation, and checks lease generation/expiry both at enqueue and immediately before each step. A DB grant starts as pending and becomes usable only after the agent persists and acknowledges that generation. Expiry or server loss forbids a new segment but lets an already-started, locally bounded indivisible flash finish; no next grant occurs until quiescence and an approved neutral receipt. A restored database generation below the agent's high-water mark forces quarantine. Physical/root/direct-probe access remains outside software fencing.

A board image arrives through the authenticated artifact endpoint with immutable digest, size, source/catalog identity, and approved flash arguments. The board agent downloads, verifies the full unstripped image before preparing any stripped flash form, and rejects corruption or missing baseline. A versioned fixture-specific neutral profile checks supervised process/fd quiescence, unexpected device owners, expected relay/power/reset states, probe and board identity, VTref/sensors, and baseline application health where available. `probe.sh` connectivity alone is not neutral proof. If the fixture lacks observability or restore, quarantine for operator inspection. The operator must approve baseline digest, permitted reset/erase/power actions, physical-clear procedure, and external peripheral profile before live use.

Initial heartbeat is 5 seconds; after 15 seconds without board-agent heartbeat, new commands stop. Human default duration is 30 minutes, CI per-app default 15 minutes and renewable under a two-hour suite ceiling, AI default 10 minutes renewable to one hour. No segment starts without remaining lease time at least its declared bound plus recovery margin. Human priority exceeds CI then AI; FIFO within class and no new lower-priority board step starts while a human waits. A second human never force-preempts the first. Extension is reasoned and bounded, with at most a 10-minute safe-wrap-up extension while another human waits. An eight-hour exceptional cap requires operator reason and physical confirmation. HIL `hil.conf` validity windows are separate from flash bounds and yield estimates. A task with no declared max segment/restore policy cannot be automatically dispatched to the board.

Board state is ready, grant_pending, active, yield_requested/draining, recovery_required, recovering, or quarantined. `board doctor` is read-only; `board recover --plan <reviewed-id> --why` runs only an allowlisted recovery plan; `board acknowledge-ready --probe <receipt-id> --physically-clear --why` requires operator authority where visual inspection is needed. `board force-release` only invalidates the old holder and starts recovery. The yield estimator uses 60 days of comparable full request-to-neutral latency, at least 30 successful samples, nearest-rank p95 plus max(5 seconds, 20 percent), floored at remaining safe-segment plus restore/probe bounds. Sparse history uses the declared bound; absent bound means unknown ETA and no automatic run. Thirty seconds is a handoff target, not a flash timeout.

Lease tokens carry board ID, generation, server UTC expiry, and nonce bound to holder identity. On receipt the board agent requires synchronized UTC with a measured worst-case offset bound at most two seconds; it seeds a local monotonic deadline as `max(0, server_expiry_utc - local_utc_now - offset_bound - 2s_safety_margin)`. Network delay is already reflected in local UTC at receipt and can only shorten the budget; no assumed one-way transit time grants authority. Every heartbeat can shorten but never lengthen the local deadline; an authorized extension creates a separately audited higher-version deadline after a fresh offset check. Unbounded clock error, heartbeat loss, agent reboot, or monotonic continuity loss forbids starting a new segment and enters recovery-required. A running indivisible segment obeys its previously declared local hard bound, not wall-clock jumps. The agent stores generation high-water and last deadline state before acknowledging a grant. No expired lease or restored database clock can extend authority.

A human holder uses `ra8ci board flash <digest>`, `probe`, `reset`, `serial attach`, or `debug start|stop` with a live lease; those commands become allowlisted agent operations rather than raw SSH/device access. UART and debugger sessions are proxied through the authenticated server to the board agent, bound to lease generation and a bounded local process group. A human can request a graceful stop or checkpoint; the agent ends its debug/serial session and verifies the fixture before release. The first live board profile is not inferred from a J-Link probe: the operator must approve the exact baseline firmware digest, fixture neutral evidence, permitted reset/erase/power actions, flash arguments, and physical-clear procedure. Until that profile is committed and tested, board mode stays disabled in production and all board tests use a simulated agent.

== Provisioning, operations, and proof

The strict Terraform/Ansible path is the starting safety reference. The direct `qm` server runner and broad Python manager destroy path are not cleanup APIs. Provisioning must preserve template ID/name/stopped state, reserved pool/datastore/bridge, run marker, local Terraform state, VM ownership checks, and stopped-state guard before purge. Use the existing `infra/terraform/environments/lab` configuration with pinned Terraform `>=1.10,<2`, bpg/proxmox `~>0.83.1`, and Vault `~>5.11.0`; existing reserved Linux 9001/template 9000/vmbr9 and Windows 9011/template 9010/vmbr8 identities permit only one prototype guest per profile. The current strict `scripts/dev/proxmox_lab_ci.sh` provides preflight and cleanup behavior, not an API to launch a long-lived GitHub runner; the Go provisioner must extract/equivalently test those guards rather than invoke its full `ci` command. Persist state under a per-run protected directory before apply; capture Terraform plan digest, module/provider versions, inventory, expected VM identity, and cleanup proof. Fixed argument-array calls run `terraform init`, `validate`, `plan`, and `apply` with `TF_DATA_DIR` and run-scoped state; cleanup validates exact marker, pool, storage, non-template, and stopped state before destroy, and preserves state on failure. Never replay create or destroy after uncertain exit without reconciling actual state.

New Ansible runner-readiness playbooks under `infra/ansible/playbooks/ra8ci-lab-linux.yml` and `ra8ci-lab-windows.yml` reuse existing lab connectivity and hardening roles but install the pinned official runner and ra8ci agent instead of running `just ci` to completion. They receive an exact per-run inventory, source-free image/version manifest, one-use agent enrollment token, and runner JIT config only after health checks; no repository shell string is an extra-var. They return a JSON proof with guest marker, OS/arch, runner/agent digests, clock/skew, disk, network reachability, and service readiness. The Go caller verifies this proof and source VM identity before JIT issuance. Replace the macOS-keychain OpenBao wrapper with a control-VM credential adapter only after a scoped credential is approved. The control-VM Terraform/Ansible declaration is separate from the disposable lab modules; no existing fixed VM ID is silently reused for it.

After PostgreSQL point-in-time restore, the server starts in reconcile-only mode with zero GitHub capacity and no board grants. It enumerates ra8ci-marked guests in the scoped Proxmox pool, archived Terraform state manifests, GitHub scale-set runners/checks, and agent heartbeats. A guest or external operation absent from restored SQL is quarantined, not adopted or destroyed by ID alone; operator-supervised reconstruction requires matching marker, pool/storage, state digest, and GitHub runner identity. If Terraform state is missing, an operator may reconstruct it with `terraform import` into a new protected run-scoped state, inspect a no-change plan and exact resource inventory, then authorize identity-checked cleanup. If import cannot establish exact identity, the guest is power-isolated and stopped under an audited break-glass procedure, then manually removed only after two-person confirmation of VM ID, marker, pool, storage volumes, non-template state, and absence of a busy runner; wildcard deletion is forbidden. If those facts cannot be proved, quarantine persists and dispatch stays drained. Missing state becomes an audit incident and a failing/pending lifecycle check. Only after every orphan has a verified disposition and board agent high-water/physical state reconciles may an operator lift drain. The restore drill must demonstrate this path, not merely that PostgreSQL starts.

An operator must approve an unused 9000+ control VM ID, management VLAN/address, storage, certificate issuer, relay/proxy path, scoped Proxmox API and GitHub App credentials, and an encrypted off-VM backup target. Initial sizing target is 4 vCPU, 16 GiB RAM, and 250 GiB protected persistent data, subject to measured sizing and Proxmox capacity. PostgreSQL uses local socket only. Draft backup target is nightly base backup plus continuous WAL with 15-minute RPO, daily artifact/Terraform-state manifest backup, 30-day retention, monthly restore to a separate VM, and four-hour RTO. Production waits for an approved destination and a successful restore drill. A restored DB forces board recovery-required until agent high-water and physical state are reconciled.

`/live` reports process life; `/ready` requires database write and audit commit, compatible schema, disk headroom, scheduler health, and backup freshness. Drain stops new assignments and grants but allows safe segments and cleanup to finish. Initial alerts cover backup/WAL lag above 15 minutes, log ingest lag above 5 minutes, agent heartbeat beyond two periods, cleanup stuck 15 minutes after worker exit, disk warning at 80 percent and critical at 90 percent, certificate expiry within 30 days, and orphan guest/board recovery. These thresholds are measured and tuned after pilot operation.

Verification requires race/coverage-clean Go gates, a disposable PostgreSQL concurrency suite for one-lease uniqueness and audit idempotency, fake GitHub/agent lost-ack tests, Linux and Windows spool/process-tree tests, log-gap/corruption tests, and DB/artifact/Terraform-state restore tests. An isolated GitHub prototype runs one Linux and one Windows job, representative `run:` and `uses:` actions, JIT expiry, cancellation, controller restart, guest boot failure, same-SHA rerun, and identity-checked cleanup. Firewall tests prove guest-to-GitHub and agent-relay access while denying management/Proxmox/DB access. Emulator verification precedes one matching board run with a live lease; no full HIL sweep. Existing `format`, `lint-go`, `test-go`, `ci-parity`, and all applicable registered gates remain required; warnings and skipped tests fail acceptance. No production deployment or legacy path removal occurs before these proofs and the operator decisions above.

Sources for this contract: #link("https://github.com/actions/scaleset/blob/v0.4.0/README.md")[GitHub scale-set client v0.4.0], #link("https://github.com/actions/scaleset/blob/v0.4.0/listener/listener.go")[pinned listener acknowledgment order], #link("https://github.com/actions/scaleset/blob/v0.4.0/types.go")[pinned job message types], #link("https://docs.github.com/en/rest/actions/workflow-jobs")[GitHub workflow-jobs API], #link("https://docs.github.com/en/rest/checks/runs")[GitHub check-run API], and #link("https://docs.github.com/en/actions/reference/runners/self-hosted-runners")[GitHub ephemeral runner guidance].
