#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Brighton Sikarskie
"""Gate: committed generated gap artefacts must match a fresh regenerate.

The MC/DC and Doxygen gap reports under ``docs/`` are GENERATED, yet they are
also COMMITTED, and nothing compared the committed copy against what the
generator produces from the current tree. On a DO-178C Level B target these are
the human-readable record of where the remaining structural-coverage and
documentation gaps are; a committed copy that has silently drifted describes a
tree that no longer exists (issue #380).

This is the "regenerate and gate" resolution -- the same shape
``check_ci_parity.py`` uses on the gate registry. For every committed generated
artefact this gate re-runs its generator and byte-compares the result against
the version committed at ``HEAD``; any difference fails the gate and names the
command that refreshes it. Deleting the committed copies (produce-in-CI-only)
was the rejected alternative: the DO-178C qualification set
(``docs/qualification/PSAC.md``, ``SVR.md``, ``SAS.md``, ``SQAP.md`` ...) cites
these files by path as versioned, retained evidence, so the in-tree history is
load-bearing and cannot move to an ephemeral CI artefact.

Two artefact families, checked uniformly:

* **mcdc-gaps** -- ``docs/MCDC_GAPS.csv``, ``docs/MCDC_GAPS.md`` and
  ``docs/MCDC_DEACTIVATIONS.md``, regenerated by
  ``scripts/fix/regen_mcdc_gaps.py`` from ``build/mcdc-report/mcdc.txt``. That
  report is the (slow) output of the ``mcdc`` gate, so this gate CONSUMES it and
  must be scheduled after ``mcdc`` in the same job; if the report is absent it
  FAILS LOUDLY naming the dependency rather than skipping.
* **doxygen-gaps** -- ``docs/DOXYGEN_GAPS.csv`` and ``docs/DOXYGEN_GAPS.md``,
  regenerated by ``scripts/checks/doxy_audit.py`` from a static source parse
  (no toolchain input required).

``--selftest`` proves the detector still fires in both directions -- a matching
regenerate passes, a mismatching one fails, and a missing required input fails
without running the generator -- so a gate that quietly stopped comparing cannot
pass as clean.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import subprocess
import sys
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_CHECKS = REPO_ROOT / "scripts" / "checks"
SCRIPTS_FIX = REPO_ROOT / "scripts" / "fix"
MCDC_TXT = REPO_ROOT / "build" / "mcdc-report" / "mcdc.txt"


@dataclass(frozen=True)
class ArtefactGroup:
    """One generator and the committed artefacts it owns.

    Attributes:
        name: Short identifier printed in gate output.
        artefacts: Repo-relative POSIX paths the generator writes and that are
            committed to the tree.
        regenerate: Runs the generator in place and returns its exit code (0 on
            success); it writes exactly ``artefacts``.
        requires: Input files that must exist before ``regenerate`` can run. An
            absent input fails the gate loudly instead of skipping the family.
        remediation: The command a human runs to refresh the committed copies.
    """

    name: str
    artefacts: tuple[str, ...]
    regenerate: Callable[[], int]
    requires: tuple[Path, ...]
    remediation: str


def _git_show_head(root: Path, rel: str) -> bytes | None:
    """Return the bytes of ``rel`` committed at ``HEAD`` in ``root``, else None."""
    result = subprocess.run(  # noqa: S603 -- fixed argv, no shell
        ["git", "-C", str(root), "show", f"HEAD:{rel}"],  # noqa: S607 -- git from PATH is intended
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    return result.stdout


def _diff_artefact(committed: bytes | None, fresh: bytes) -> str | None:
    """Describe how a committed copy differs from a fresh regenerate.

    Args:
        committed: Bytes committed at HEAD, or None when the file is untracked.
        fresh: Bytes the generator just produced.

    Returns:
        A one-line drift description, or None when the two are byte-identical.
    """
    if committed is None:
        return "committed copy is not tracked at HEAD; cannot verify freshness"
    if committed == fresh:
        return None
    return f"stale: committed {len(committed)} bytes differ from the {len(fresh)}-byte regenerate"


def _restore(root: Path, saved: dict[str, bytes | None]) -> None:
    """Put every artefact back to the bytes captured before regeneration."""
    for rel, data in saved.items():
        path = root / rel
        if data is None:
            path.unlink(missing_ok=True)
        else:
            path.write_bytes(data)


def _check_group(
    group: ArtefactGroup,
    root: Path,
    read_committed: Callable[[Path, str], bytes | None],
) -> list[str]:
    """Regenerate one group and return a drift message per stale artefact.

    Restores every artefact to its pre-run bytes afterwards, so the check never
    leaves the working tree dirtier than it found it. A missing required input
    is a hard failure -- the generator is never run -- rather than a skip.
    """
    missing = [str(p) for p in group.requires if not p.exists()]
    if missing:
        joined = ", ".join(missing)
        return [
            f"{group.name}: required input(s) absent: {joined}. This gate consumes them "
            f"and must run after the gate that produces them. {group.remediation}"
        ]

    committed = {rel: read_committed(root, rel) for rel in group.artefacts}
    saved: dict[str, bytes | None] = {}
    for rel in group.artefacts:
        path = root / rel
        saved[rel] = path.read_bytes() if path.exists() else None

    errors: list[str] = []
    try:
        rc = group.regenerate()
        if rc != 0:
            errors.append(f"{group.name}: regenerator exited {rc} (see its output above)")
        else:
            for rel in group.artefacts:
                drift = _diff_artefact(committed[rel], (root / rel).read_bytes())
                if drift is not None:
                    errors.append(f"{rel}: {drift}. {group.remediation}")
    finally:
        _restore(root, saved)
    return errors


def _regenerate_mcdc() -> int:
    """Rewrite docs/MCDC_GAPS.* from build/mcdc-report/mcdc.txt; return its rc."""
    if str(SCRIPTS_FIX) not in sys.path:
        sys.path.insert(0, str(SCRIPTS_FIX))
    import regen_mcdc_gaps  # noqa: PLC0415 -- lazy: adds scripts/fix to sys.path first

    with contextlib.redirect_stdout(io.StringIO()):
        return regen_mcdc_gaps.main()


def _regenerate_doxygen() -> int:
    """Rewrite docs/DOXYGEN_GAPS.* from a static source parse; return its rc."""
    if str(SCRIPTS_CHECKS) not in sys.path:
        sys.path.insert(0, str(SCRIPTS_CHECKS))
    import doxy_report  # noqa: PLC0415 -- lazy: adds scripts/checks to sys.path first

    with contextlib.redirect_stdout(io.StringIO()):
        return doxy_report.run_report()


def _production_groups() -> list[ArtefactGroup]:
    """The committed generated gap artefacts this gate enforces freshness on."""
    return [
        ArtefactGroup(
            name="mcdc-gaps",
            artefacts=(
                "docs/MCDC_GAPS.csv",
                "docs/MCDC_GAPS.md",
                "docs/MCDC_DEACTIVATIONS.md",
            ),
            regenerate=_regenerate_mcdc,
            requires=(MCDC_TXT,),
            remediation=(
                "Run `make mcdc` (or `bash scripts/ci.sh --gate mcdc`) and commit the "
                "regenerated docs/MCDC_GAPS.csv, docs/MCDC_GAPS.md and "
                "docs/MCDC_DEACTIVATIONS.md."
            ),
        ),
        ArtefactGroup(
            name="doxygen-gaps",
            artefacts=("docs/DOXYGEN_GAPS.csv", "docs/DOXYGEN_GAPS.md"),
            regenerate=_regenerate_doxygen,
            requires=(),
            remediation=(
                "Run `python3 scripts/checks/doxy_audit.py` and commit the regenerated "
                "docs/DOXYGEN_GAPS.csv and docs/DOXYGEN_GAPS.md."
            ),
        ),
    ]


def check() -> int:
    """Fail when any committed generated artefact differs from a fresh regenerate."""
    errors: list[str] = []
    for group in _production_groups():
        errors.extend(_check_group(group, REPO_ROOT, _git_show_head))
    if errors:
        sys.stderr.write("check_generated_artefacts.py: committed gap artefacts are stale.\n\n")
        for error in errors:
            sys.stderr.write(f"  {error}\n\n")
        sys.stderr.write(f"{len(errors)} stale artefact(s).\n")
        return 1
    print(
        "check_generated_artefacts.py: clean -- every committed gap artefact "
        "matches a fresh regenerate."
    )
    return 0


def _synthetic_generator(path: Path, content: bytes) -> Callable[[], int]:
    """Build a regenerate() that writes fixed ``content`` to ``path`` and succeeds."""

    def _regenerate() -> int:
        path.write_bytes(content)
        return 0

    return _regenerate


def _counting_generator(sink: list[int], path: Path) -> Callable[[], int]:
    """Build a regenerate() that records each call in ``sink`` before writing."""

    def _regenerate() -> int:
        sink.append(1)
        path.write_bytes(b"regenerated\n")
        return 0

    return _regenerate


def _run_git(root: Path, *args: str) -> None:
    """Run a git subcommand in ``root``, raising on non-zero exit."""
    subprocess.run(  # noqa: S603 -- fixed argv, no shell
        ["git", "-C", str(root), *args],  # noqa: S607 -- git from PATH is intended
        check=True,
        capture_output=True,
    )


def _selftest_cases(root: Path) -> list[tuple[str, bool]]:
    """Exercise every detector direction against a throwaway git repo in ``root``.

    Returns one ``(label, passed)`` tuple per direction: a fresh regenerate that
    matches the committed copy is clean, one that differs is drift, a missing
    required input fails without running the generator, and an untracked
    committed copy is drift.
    """
    tracked = "docs/SYNTH_GAPS.md"
    (root / "docs").mkdir(parents=True, exist_ok=True)
    (root / tracked).write_bytes(b"committed-AAA\n")
    _run_git(root, "init", "-q")
    _run_git(root, "add", "-A")
    _run_git(
        root, "-c", "user.email=ci@localhost", "-c", "user.name=ci", "commit", "-q", "-m", "seed"
    )

    match_group = ArtefactGroup(
        "synth-match",
        (tracked,),
        _synthetic_generator(root / tracked, b"committed-AAA\n"),
        (),
        "n/a",
    )
    drift_group = ArtefactGroup(
        "synth-drift",
        (tracked,),
        _synthetic_generator(root / tracked, b"regenerated-BBB\n"),
        (),
        "n/a",
    )
    ran: list[int] = []
    missing_group = ArtefactGroup(
        "synth-missing",
        (tracked,),
        _counting_generator(ran, root / tracked),
        (root / "absent-input.txt",),
        "n/a",
    )
    untracked = "docs/NOT_COMMITTED.md"
    untracked_group = ArtefactGroup(
        "synth-untracked",
        (untracked,),
        _synthetic_generator(root / untracked, b"y\n"),
        (),
        "n/a",
    )

    match_clean = _check_group(match_group, root, _git_show_head) == []
    drift_seen = bool(_check_group(drift_group, root, _git_show_head))
    missing_errors = _check_group(missing_group, root, _git_show_head)
    untracked_drift = bool(_check_group(untracked_group, root, _git_show_head))
    return [
        ("fresh matches committed -> clean", match_clean),
        ("fresh differs from committed -> drift", drift_seen),
        ("missing required input -> fail, generator not run", bool(missing_errors) and not ran),
        ("untracked committed copy -> drift", untracked_drift),
    ]


def selftest() -> int:
    """Prove the detector fires in both directions and never silently skips."""
    with tempfile.TemporaryDirectory() as tmp:
        cases = _selftest_cases(Path(tmp))
    failures = 0
    for label, passed in cases:
        status = "ok" if passed else "FAIL"
        if not passed:
            failures += 1
        print(f"  [{status}] {label}")
    if failures:
        sys.stderr.write(f"check_generated_artefacts.py --selftest: {failures} case(s) failed.\n")
        return 1
    print("check_generated_artefacts.py --selftest: all cases pass.")
    return 0


def main() -> int:
    """Parse arguments and dispatch to the freshness check or its selftest."""
    parser = argparse.ArgumentParser(
        description="Verify committed generated gap artefacts match a fresh regenerate."
    )
    parser.add_argument(
        "--selftest",
        action="store_true",
        help="run the detector's self-test (both directions) and exit",
    )
    args = parser.parse_args()
    if args.selftest:
        return selftest()
    return check()


if __name__ == "__main__":
    raise SystemExit(main())
