#!/usr/bin/env python3
# Copyright (c) 2026 Brighton Sikarskie
# SPDX-License-Identifier: MIT
"""generate.py -- JSON-driven configurator for ra8d2-firmware.

Reads a JSON config (validated against tools/ra_qe/schema/config.schema.json)
and emits hand-written-style C23 source/header pairs:

    gen_clocks.{c,h}   ra_cgc_init() body + clock-tree typed enums
    gen_pinmux.{c,h}   ra_gpio init table (port/pin/mode/level)
    gen_irq.{c,h}      ICU vector table entries (name/vector/priority/handler)
    gen_mstp.{c,h}     module-stop release calls

This is the hand-rolled, command-line equivalent of the Renesas QE / SCFG
tool. The user's standing rule for ra8d2-firmware is "no e2 studio, ever":
generated artifacts must look like code a human would write under
CLAUDE.md style (C23 typed enums, #pragma once, full Doxygen, no malloc).

Usage:
    python3 generate.py --config FOO.json --output-dir DIR

Stdlib only. JSON Schema is validated by a small built-in walker -- no
external `jsonschema` package needed (the project policy is to vendor
third-party libs directly, not pip-install them).
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Any

THIS_DIR = pathlib.Path(__file__).resolve().parent
SCHEMA_PATH = THIS_DIR / "schema" / "config.schema.json"

COPYRIGHT_LINES = (
    " * @copyright Copyright (c) 2026 Brighton Sikarskie",
    " * SPDX-License-Identifier: MIT",
)

GEN_BANNER = (
    "/* AUTO-GENERATED by tools/ra_qe/generate.py -- DO NOT EDIT BY HAND. */"
)


# ---------------------------------------------------------------------------
# Minimal JSON Schema validator (subset sufficient for our schema).
# ---------------------------------------------------------------------------
class SchemaError(ValueError):
    """Raised when a config document fails schema validation."""


def _validate(node: Any, schema: dict, path: str = "$") -> None:
    """Validate `node` against `schema`. Supports the subset used by
    config.schema.json: type, enum, required, properties,
    additionalProperties, items, minimum, maximum, pattern.
    """
    t = schema.get("type")
    if t == "object":
        if not isinstance(node, dict):
            raise SchemaError(f"{path}: expected object, got {type(node).__name__}")
        required = schema.get("required", [])
        for key in required:
            if key not in node:
                raise SchemaError(f"{path}: missing required key '{key}'")
        props = schema.get("properties", {})
        if schema.get("additionalProperties") is False:
            for key in node:
                if key not in props:
                    raise SchemaError(f"{path}: unexpected key '{key}'")
        for key, val in node.items():
            if key in props:
                _validate(val, props[key], f"{path}.{key}")
    elif t == "array":
        if not isinstance(node, list):
            raise SchemaError(f"{path}: expected array, got {type(node).__name__}")
        item_schema = schema.get("items")
        if item_schema is not None:
            for i, item in enumerate(node):
                _validate(item, item_schema, f"{path}[{i}]")
    elif t == "string":
        if not isinstance(node, str):
            raise SchemaError(f"{path}: expected string, got {type(node).__name__}")
        if "enum" in schema and node not in schema["enum"]:
            raise SchemaError(
                f"{path}: '{node}' not in enum {schema['enum']}"
            )
        if "pattern" in schema and not re.match(schema["pattern"], node):
            raise SchemaError(f"{path}: '{node}' violates pattern {schema['pattern']}")
    elif t == "integer":
        if isinstance(node, bool) or not isinstance(node, int):
            raise SchemaError(f"{path}: expected integer, got {type(node).__name__}")
        if "minimum" in schema and node < schema["minimum"]:
            raise SchemaError(f"{path}: {node} < minimum {schema['minimum']}")
        if "maximum" in schema and node > schema["maximum"]:
            raise SchemaError(f"{path}: {node} > maximum {schema['maximum']}")
    elif t == "number":
        if isinstance(node, bool) or not isinstance(node, (int, float)):
            raise SchemaError(f"{path}: expected number, got {type(node).__name__}")
        if "minimum" in schema and node < schema["minimum"]:
            raise SchemaError(f"{path}: {node} < minimum {schema['minimum']}")
    elif t == "boolean":
        if not isinstance(node, bool):
            raise SchemaError(f"{path}: expected boolean, got {type(node).__name__}")


def validate_config(config: dict, schema: dict) -> None:
    """Validate top-level config dict against the loaded schema."""
    _validate(config, schema, "$")


# ---------------------------------------------------------------------------
# Helpers for generating C source.
# ---------------------------------------------------------------------------
def _doxy_header(filename: str, brief: str, app: str) -> str:
    """Build a Doxygen file header that matches CLAUDE.md style."""
    return (
        "/**\n"
        f" * @file {filename}\n"
        f" * @brief {brief}\n"
        " *\n"
        " * @details\n"
        f" * Generated from a tools/ra_qe JSON config for app '{app}'.\n"
        " * Edits to this file will be lost the next time the configurator\n"
        " * is regenerated -- modify the source JSON instead.\n"
        " *\n"
        + "\n".join(COPYRIGHT_LINES)
        + "\n */\n"
    )


def _open_header(filename: str, brief: str, app: str) -> str:
    return _doxy_header(filename, brief, app) + "\n" + GEN_BANNER + "\n\n#pragma once\n\n#include <stdint.h>\n\n"


def _open_source(filename: str, brief: str, app: str, header_name: str) -> str:
    return (
        _doxy_header(filename, brief, app)
        + "\n"
        + GEN_BANNER
        + f'\n\n#include "{header_name}"\n\n'
    )


# ---------------------------------------------------------------------------
# Code generators.
# ---------------------------------------------------------------------------
def gen_clocks(config: dict) -> tuple[str, str]:
    """Emit gen_clocks.h / gen_clocks.c."""
    app = config["app"]
    clocks = config["clocks"]
    src_field_pairs = [
        ("moco", "k_clock_src_moco"),
        ("hoco", "k_clock_src_hoco"),
        ("loco", "k_clock_src_loco"),
        ("main_osc", "k_clock_src_main_osc"),
        ("sub_osc", "k_clock_src_sub_osc"),
        ("pll1", "k_clock_src_pll1"),
        ("pll2", "k_clock_src_pll2"),
    ]

    enum_lines = ",\n".join(f"    {tag} = {i}" for i, (_, tag) in enumerate(src_field_pairs))

    header = _open_header("gen_clocks.h", "Generated clock-tree configuration", app)
    header += (
        "/**\n"
        " * @brief Identifier for the primary system clock source.\n"
        " *\n"
        " * @details Mirrors SCKSCR.CKSEL field encodings.\n"
        " */\n"
        "typedef enum : uint8_t {\n"
        f"{enum_lines}\n"
        "} clock_source_t;\n\n"
        "/**\n"
        " * @brief Compile-time clock-tree summary for this app.\n"
        " *\n"
        " * @details Populated by tools/ra_qe/generate.py from the JSON config.\n"
        " * Frequencies are stored in Hz to keep the type integral.\n"
        " */\n"
        "typedef struct {\n"
        "    clock_source_t source;     /**< Active source after init. */\n"
        "    uint32_t       cpuclk0_hz; /**< CPUCLK0 frequency in Hz. */\n"
        "    uint32_t       iclk_hz;    /**< ICLK frequency in Hz.    */\n"
        "    uint32_t       pclka_hz;   /**< PCLKA frequency in Hz.   */\n"
        "    uint32_t       pclkb_hz;   /**< PCLKB frequency in Hz.   */\n"
        "} clock_config_t;\n\n"
        "/**\n"
        " * @brief Read-only clock summary derived from the JSON config.\n"
        " *\n"
        " * @details Lives in .rodata. NASA Rule 3 compliant -- statically allocated.\n"
        " */\n"
        "extern const clock_config_t g_gen_clock_config;\n\n"
        "/**\n"
        " * @brief Hook invoked from ra_cgc_init() in user code.\n"
        " *\n"
        " * @details Today this is a no-op stub: the real PLL bring-up\n"
        " * lives in libs/ra_hal/src/ra_cgc.c. The configurator emits this\n"
        " * symbol so app-specific clock policy can be linked in without\n"
        " * touching the shared HAL.\n"
        " *\n"
        " * @return 0 on success, non-zero on failure.\n"
        " * @pre Power has been applied.\n"
        " * @pre Module-stop release for CGC has been performed.\n"
        " * @post g_gen_clock_config matches the active clock tree.\n"
        " * @post No interrupts unmasked by this function.\n"
        " * @note Not thread-safe; call once from init.\n"
        " * @since 0.1.0\n"
        " */\n"
        "int32_t gen_clocks_apply(void);\n"
    )

    enum_for_source = dict(src_field_pairs)[clocks["source"]]
    src = _open_source("gen_clocks.c", "Generated clock-tree configuration", app, "gen_clocks.h")
    src += (
        "const clock_config_t g_gen_clock_config = {\n"
        f"    .source     = {enum_for_source},\n"
        f"    .cpuclk0_hz = {int(clocks.get('cpuclk0_hz', 0))}u,\n"
        f"    .iclk_hz    = {int(clocks.get('iclk_hz', 0))}u,\n"
        f"    .pclka_hz   = {int(clocks.get('pclka_hz', 0))}u,\n"
        f"    .pclkb_hz   = {int(clocks.get('pclkb_hz', 0))}u,\n"
        "};\n\n"
        "int32_t gen_clocks_apply(void) {\n"
        "    /* Hook for app-specific clock-tree bring-up.\n"
        "     * Real PLL programming lives in libs/ra_hal/src/ra_cgc.c. */\n"
        "    return 0;\n"
        "}\n"
    )
    return header, src


def gen_pinmux(config: dict) -> tuple[str, str]:
    app = config["app"]
    pins = config["pinmux"]

    mode_map = {
        "output": "k_pin_mode_output",
        "input": "k_pin_mode_input",
        "input_pullup": "k_pin_mode_input_pullup",
        "peripheral": "k_pin_mode_peripheral",
        "analog": "k_pin_mode_analog",
    }
    level_map = {"low": "k_pin_level_low", "high": "k_pin_level_high"}

    header = _open_header("gen_pinmux.h", "Generated pinmux table", app)
    header += (
        "/**\n"
        " * @brief Pin direction / function. Mirrors PFS field shapes.\n"
        " */\n"
        "typedef enum : uint8_t {\n"
        "    k_pin_mode_output         = 0,\n"
        "    k_pin_mode_input          = 1,\n"
        "    k_pin_mode_input_pullup   = 2,\n"
        "    k_pin_mode_peripheral     = 3,\n"
        "    k_pin_mode_analog         = 4\n"
        "} pin_mode_t;\n\n"
        "/**\n"
        " * @brief Initial output level for output-mode pins.\n"
        " */\n"
        "typedef enum : uint8_t {\n"
        "    k_pin_level_low  = 0,\n"
        "    k_pin_level_high = 1\n"
        "} pin_level_t;\n\n"
        "/**\n"
        " * @brief One row of the generated pinmux table.\n"
        " */\n"
        "typedef struct {\n"
        "    uint8_t     port;          /**< Port index (0..11).         */\n"
        "    uint8_t     pin;           /**< Pin index within port.       */\n"
        "    pin_mode_t  mode;          /**< Direction / function.        */\n"
        "    pin_level_t initial_level; /**< Output level at init.        */\n"
        "} pinmux_entry_t;\n\n"
    )

    if pins:
        # Symbolic labels become a typed enum so app code can index by name.
        labels = [(p["label"], i) for i, p in enumerate(pins) if p.get("label")]
        if labels:
            header += (
                "/**\n"
                " * @brief Symbolic indices into g_gen_pinmux_table.\n"
                " */\n"
                "typedef enum : uint8_t {\n"
            )
            header += ",\n".join(f"    k_pin_idx_{lbl} = {idx}" for lbl, idx in labels)
            header += "\n} pin_label_t;\n\n"

    # When count is 0 the C array still needs at least one element. The
    # storage enum mirrors the declared array size (max(count, 1)) so the
    # extern declaration and the definition always match.
    storage_count = max(len(pins), 1)
    header += (
        f"/** @brief Number of pinmux rows actually populated. */\n"
        "typedef enum : uint8_t {\n"
        f"    k_gen_pinmux_count   = {len(pins)},\n"
        f"    k_gen_pinmux_storage = {storage_count}\n"
        "} gen_pinmux_count_t;\n\n"
        "/**\n"
        " * @brief Read-only pinmux table.\n"
        " * @details Statically allocated (NASA Rule 3 compliant).\n"
        " * @since 0.1.0\n"
        " */\n"
        "extern const pinmux_entry_t g_gen_pinmux_table[k_gen_pinmux_storage];\n"
    )

    src = _open_source("gen_pinmux.c", "Generated pinmux table", app, "gen_pinmux.h")
    if not pins:
        src += (
            "/* Empty pinmux: count == 0 but C requires at least one element\n"
            " * for a non-extern definition. The single zero row is never\n"
            " * read because k_gen_pinmux_count is 0. */\n"
            "const pinmux_entry_t g_gen_pinmux_table[k_gen_pinmux_storage] = {\n"
            "    { .port = 0u, .pin = 0u, .mode = k_pin_mode_input, .initial_level = k_pin_level_low }\n"
            "};\n"
        )
    else:
        rows = []
        for p in pins:
            mode_c = mode_map[p["mode"]]
            lvl_c = level_map.get(p.get("initial_level", "low"), "k_pin_level_low")
            label = p.get("label", f"port{p['port']}_pin{p['pin']}")
            rows.append(
                f"    /* {label} */\n"
                f"    {{ .port = {int(p['port'])}u, .pin = {int(p['pin'])}u, "
                f".mode = {mode_c}, .initial_level = {lvl_c} }}"
            )
        src += (
            "const pinmux_entry_t g_gen_pinmux_table[k_gen_pinmux_storage] = {\n"
            + ",\n".join(rows)
            + "\n};\n"
        )
    return header, src


def gen_irq(config: dict) -> tuple[str, str]:
    app = config["app"]
    irqs = config["irqs"]

    storage_count = max(len(irqs), 1)
    header = _open_header("gen_irq.h", "Generated ICU vector table", app)
    header += (
        "/**\n"
        " * @brief One row of the generated IRQ table.\n"
        " */\n"
        "typedef struct {\n"
        "    uint8_t      vector;   /**< ICU slot (0..95).      */\n"
        "    uint8_t      priority; /**< NVIC priority (0..15). */\n"
        "    void       (*handler)(void); /**< ISR entry point. */\n"
        "} irq_entry_t;\n\n"
        f"typedef enum : uint8_t {{\n"
        f"    k_gen_irq_count   = {len(irqs)},\n"
        f"    k_gen_irq_storage = {storage_count}\n"
        f"}} gen_irq_count_t;\n\n"
    )
    if irqs:
        header += "/**\n * @brief Symbolic IRQ identifiers (indices into g_gen_irq_table).\n */\ntypedef enum : uint8_t {\n"
        header += ",\n".join(f"    k_irq_id_{i['name']} = {idx}" for idx, i in enumerate(irqs))
        header += "\n} irq_id_t;\n\n"
        # Forward declare each handler.
        for i in irqs:
            handler = i.get("handler", f"{i['name']}_isr")
            header += f"/** @brief Handler for {i['name']}. @since 0.1.0 */\nvoid {handler}(void);\n"
        header += "\n"

    header += (
        "/**\n"
        " * @brief Read-only IRQ table.\n"
        " * @since 0.1.0\n"
        " */\n"
        "extern const irq_entry_t g_gen_irq_table[k_gen_irq_storage];\n"
    )

    src = _open_source("gen_irq.c", "Generated ICU vector table", app, "gen_irq.h")
    if not irqs:
        src += (
            "/* No IRQs in config: emit a single zero row to keep the symbol\n"
            " * defined; never indexed because k_gen_irq_count is 0. */\n"
            "static void gen_irq_unused_handler_(void) { /* no-op */ }\n"
            "const irq_entry_t g_gen_irq_table[k_gen_irq_storage] = {\n"
            "    { .vector = 0u, .priority = 0u, .handler = gen_irq_unused_handler_ }\n"
            "};\n"
        )
    else:
        rows = []
        for i in irqs:
            handler = i.get("handler", f"{i['name']}_isr")
            rows.append(
                f"    /* {i['name']} */\n"
                f"    {{ .vector = {int(i['vector'])}u, .priority = {int(i['priority'])}u, "
                f".handler = {handler} }}"
            )
        src += (
            "const irq_entry_t g_gen_irq_table[k_gen_irq_storage] = {\n"
            + ",\n".join(rows)
            + "\n};\n"
        )
    return header, src


def gen_mstp(config: dict) -> tuple[str, str]:
    app = config["app"]
    entries = config["mstp"]

    storage_count = max(len(entries), 1)
    header = _open_header("gen_mstp.h", "Generated module-stop release list", app)
    header += (
        "/**\n"
        " * @brief One module-stop action.\n"
        " */\n"
        "typedef struct {\n"
        "    const char *module; /**< Module identifier (e.g. \"ioport\"). */\n"
        "    uint8_t     enable; /**< 1 = release from stop, 0 = place in stop. */\n"
        "} mstp_entry_t;\n\n"
        f"typedef enum : uint8_t {{\n"
        f"    k_gen_mstp_count   = {len(entries)},\n"
        f"    k_gen_mstp_storage = {storage_count}\n"
        f"}} gen_mstp_count_t;\n\n"
        "/**\n"
        " * @brief Read-only MSTP action list.\n"
        " * @since 0.1.0\n"
        " */\n"
        "extern const mstp_entry_t g_gen_mstp_table[k_gen_mstp_storage];\n"
    )

    src = _open_source("gen_mstp.c", "Generated module-stop release list", app, "gen_mstp.h")
    if not entries:
        src += (
            "/* Empty MSTP list: emit a zero row to keep the symbol defined. */\n"
            "const mstp_entry_t g_gen_mstp_table[k_gen_mstp_storage] = {\n"
            "    { .module = \"\", .enable = 0u }\n"
            "};\n"
        )
    else:
        rows = []
        for e in entries:
            rows.append(
                f"    {{ .module = \"{e['module']}\", .enable = {1 if e['enable'] else 0}u }}"
            )
        src += (
            "const mstp_entry_t g_gen_mstp_table[k_gen_mstp_storage] = {\n"
            + ",\n".join(rows)
            + "\n};\n"
        )
    return header, src


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate C tables from a JSON config (Renesas QE-style).")
    parser.add_argument("--config", required=True, help="Path to JSON config.")
    parser.add_argument("--output-dir", required=True, help="Directory to emit gen_*.{c,h} into.")
    parser.add_argument("--schema", default=str(SCHEMA_PATH), help="Path to JSON schema.")
    args = parser.parse_args(argv)

    config_path = pathlib.Path(args.config)
    out_dir = pathlib.Path(args.output_dir)
    schema_path = pathlib.Path(args.schema)

    if not config_path.is_file():
        print(f"error: config not found: {config_path}", file=sys.stderr)
        return 2
    if not schema_path.is_file():
        print(f"error: schema not found: {schema_path}", file=sys.stderr)
        return 2

    config = json.loads(config_path.read_text(encoding="utf-8"))
    schema = json.loads(schema_path.read_text(encoding="utf-8"))

    try:
        validate_config(config, schema)
    except SchemaError as exc:
        print(f"schema validation failed: {exc}", file=sys.stderr)
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)

    artifacts = {
        "gen_clocks": gen_clocks(config),
        "gen_pinmux": gen_pinmux(config),
        "gen_irq": gen_irq(config),
        "gen_mstp": gen_mstp(config),
    }
    for name, (hdr, src) in artifacts.items():
        (out_dir / f"{name}.h").write_text(hdr, encoding="utf-8")
        (out_dir / f"{name}.c").write_text(src, encoding="utf-8")
        print(f"wrote {out_dir / (name + '.h')}")
        print(f"wrote {out_dir / (name + '.c')}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
